FROM rocker/r-ver:4.5.0

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates gnupg && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y --no-install-recommends nodejs && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN R -e "install.packages('jmvtools', repos = c('https://repo.jamovi.org', 'https://cran.r-project.org'))"

WORKDIR /root
CMD ["bash"]
