
# This file is automatically generated, you probably don't want to edit this

anovaCheckOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovaCheckOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            factors = NULL,
            reportLang = "en",
            showPlots = TRUE,
            plotSet = "complete",
            residSmoother = "none",
            residShowBand = FALSE,
            residRefLine = TRUE,
            influenceLabelMode = "top5",
            influenceShowThreshold = TRUE,
            plotStyle = "clean",
            plotPalette = "blueOrange", ...) {

            super$initialize(
                package="AssumptionsLab",
                name="anovaCheck",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"),
                default="en")
            private$..showPlots <- jmvcore::OptionBool$new(
                "showPlots",
                showPlots,
                default=TRUE)
            private$..plotSet <- jmvcore::OptionList$new(
                "plotSet",
                plotSet,
                options=list(
                    "basic",
                    "normality",
                    "influence",
                    "complete"),
                default="complete")
            private$..residSmoother <- jmvcore::OptionList$new(
                "residSmoother",
                residSmoother,
                options=list(
                    "none",
                    "loess",
                    "linear"),
                default="none")
            private$..residShowBand <- jmvcore::OptionBool$new(
                "residShowBand",
                residShowBand,
                default=FALSE)
            private$..residRefLine <- jmvcore::OptionBool$new(
                "residRefLine",
                residRefLine,
                default=TRUE)
            private$..influenceLabelMode <- jmvcore::OptionList$new(
                "influenceLabelMode",
                influenceLabelMode,
                options=list(
                    "none",
                    "cooks",
                    "leverage",
                    "studres",
                    "top5"),
                default="top5")
            private$..influenceShowThreshold <- jmvcore::OptionBool$new(
                "influenceShowThreshold",
                influenceShowThreshold,
                default=TRUE)
            private$..plotStyle <- jmvcore::OptionList$new(
                "plotStyle",
                plotStyle,
                options=list(
                    "clean",
                    "bw",
                    "contrast",
                    "fullColor"),
                default="clean")
            private$..plotPalette <- jmvcore::OptionList$new(
                "plotPalette",
                plotPalette,
                options=list(
                    "blueOrange",
                    "viridis",
                    "greyscale",
                    "colorblind"),
                default="blueOrange")

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..factors)
            self$.addOption(private$..reportLang)
            self$.addOption(private$..showPlots)
            self$.addOption(private$..plotSet)
            self$.addOption(private$..residSmoother)
            self$.addOption(private$..residShowBand)
            self$.addOption(private$..residRefLine)
            self$.addOption(private$..influenceLabelMode)
            self$.addOption(private$..influenceShowThreshold)
            self$.addOption(private$..plotStyle)
            self$.addOption(private$..plotPalette)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        factors = function() private$..factors$value,
        reportLang = function() private$..reportLang$value,
        showPlots = function() private$..showPlots$value,
        plotSet = function() private$..plotSet$value,
        residSmoother = function() private$..residSmoother$value,
        residShowBand = function() private$..residShowBand$value,
        residRefLine = function() private$..residRefLine$value,
        influenceLabelMode = function() private$..influenceLabelMode$value,
        influenceShowThreshold = function() private$..influenceShowThreshold$value,
        plotStyle = function() private$..plotStyle$value,
        plotPalette = function() private$..plotPalette$value),
    private = list(
        ..dep = NA,
        ..covs = NA,
        ..factors = NA,
        ..reportLang = NA,
        ..showPlots = NA,
        ..plotSet = NA,
        ..residSmoother = NA,
        ..residShowBand = NA,
        ..residRefLine = NA,
        ..influenceLabelMode = NA,
        ..influenceShowThreshold = NA,
        ..plotStyle = NA,
        ..plotPalette = NA)
)

anovaCheckResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovaCheckResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        designGuide = function() private$.items[["designGuide"]],
        designSummary = function() private$.items[["designSummary"]],
        cellSummary = function() private$.items[["cellSummary"]],
        designInterpretation = function() private$.items[["designInterpretation"]],
        diagnosticPlotsGuide = function() private$.items[["diagnosticPlotsGuide"]],
        groupBoxplotsPlot = function() private$.items[["groupBoxplotsPlot"]],
        groupBoxplotsGuide = function() private$.items[["groupBoxplotsGuide"]],
        residualNormalityGuide = function() private$.items[["residualNormalityGuide"]],
        residualNormality = function() private$.items[["residualNormality"]],
        residualNormalityInterpretation = function() private$.items[["residualNormalityInterpretation"]],
        residualsFittedPlot = function() private$.items[["residualsFittedPlot"]],
        residualsFittedGuide = function() private$.items[["residualsFittedGuide"]],
        qqResidualsPlot = function() private$.items[["qqResidualsPlot"]],
        qqResidualsGuide = function() private$.items[["qqResidualsGuide"]],
        residualHistogramPlot = function() private$.items[["residualHistogramPlot"]],
        residualHistogramGuide = function() private$.items[["residualHistogramGuide"]],
        residualNormalCurvePlot = function() private$.items[["residualNormalCurvePlot"]],
        residualNormalCurveGuide = function() private$.items[["residualNormalCurveGuide"]],
        varianceGuide = function() private$.items[["varianceGuide"]],
        varianceTests = function() private$.items[["varianceTests"]],
        varianceInterpretation = function() private$.items[["varianceInterpretation"]],
        slopesGuide = function() private$.items[["slopesGuide"]],
        slopesTests = function() private$.items[["slopesTests"]],
        slopesInterpretation = function() private$.items[["slopesInterpretation"]],
        covariateLinearityGuide = function() private$.items[["covariateLinearityGuide"]],
        covariateLinearity = function() private$.items[["covariateLinearity"]],
        covariateLinearityInterpretation = function() private$.items[["covariateLinearityInterpretation"]],
        multicollinearityGuide = function() private$.items[["multicollinearityGuide"]],
        multicollinearity = function() private$.items[["multicollinearity"]],
        multicollinearityInterpretation = function() private$.items[["multicollinearityInterpretation"]],
        correlationMatrixGuide = function() private$.items[["correlationMatrixGuide"]],
        pearsonMatrixTable = function() private$.items[["pearsonMatrixTable"]],
        dcorMatrixTable = function() private$.items[["dcorMatrixTable"]],
        correlationMatrixNote = function() private$.items[["correlationMatrixNote"]],
        correlationComparisonGuide = function() private$.items[["correlationComparisonGuide"]],
        correlationComparisonTable = function() private$.items[["correlationComparisonTable"]],
        correlationComparisonInterpretation = function() private$.items[["correlationComparisonInterpretation"]],
        influenceGuide = function() private$.items[["influenceGuide"]],
        influence = function() private$.items[["influence"]],
        influenceInterpretation = function() private$.items[["influenceInterpretation"]],
        residualsLeveragePlot = function() private$.items[["residualsLeveragePlot"]],
        residualsLeverageGuide = function() private$.items[["residualsLeverageGuide"]],
        cooksDPlot = function() private$.items[["cooksDPlot"]],
        cooksDGuide = function() private$.items[["cooksDGuide"]],
        independenceGuide = function() private$.items[["independenceGuide"]],
        alternativesGuide = function() private$.items[["alternativesGuide"]],
        alternatives = function() private$.items[["alternatives"]],
        alternativesWhen = function() private$.items[["alternativesWhen"]],
        notes = function() private$.items[["notes"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="ANOVA/ANCOVA")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="ANOVA/ANCOVA"))
            self$add(jmvcore::Html$new(
                options=options,
                name="designGuide",
                title="Dise\u00F1o del modelo"))
            self$add(jmvcore::Table$new(
                options=options,
                name="designSummary",
                title="Resumen del dise\u00F1o",
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Elemento", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cellSummary",
                title="Tama\u00F1o de celdas y balance",
                columns=list(
                    list(
                        `name`="cell", 
                        `title`="Celda / grupo", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="n", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="M", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="variance", 
                        `title`="Varianza", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="designInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Html$new(
                options=options,
                name="diagnosticPlotsGuide",
                title="Gr\u00E1ficos diagn\u00F3sticos de ANOVA/ANCOVA"))
            self$add(jmvcore::Image$new(
                options=options,
                name="groupBoxplotsPlot",
                title="Variable dependiente por grupo",
                width=600,
                height=340,
                renderFun=".plotGroupBoxplots"))
            self$add(jmvcore::Html$new(
                options=options,
                name="groupBoxplotsGuide",
                title="Gu\u00EDa: Variable dependiente por grupo"))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualNormalityGuide",
                title="Normalidad de residuos"))
            self$add(jmvcore::Table$new(
                options=options,
                name="residualNormality",
                title="Normalidad de residuos",
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Prueba", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualNormalityInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualsFittedPlot",
                title="Residuos vs valores ajustados",
                width=560,
                height=315,
                renderFun=".plotResidualsFitted"))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualsFittedGuide",
                title="Gu\u00EDa: Residuos vs valores ajustados"))
            self$add(jmvcore::Image$new(
                options=options,
                name="qqResidualsPlot",
                title="Q-Q plot de residuos",
                width=560,
                height=310,
                renderFun=".plotQQResiduals"))
            self$add(jmvcore::Html$new(
                options=options,
                name="qqResidualsGuide",
                title="Gu\u00EDa: Q-Q plot de residuos"))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualHistogramPlot",
                title="Histograma de residuos",
                width=560,
                height=300,
                renderFun=".plotResidualHistogram"))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualHistogramGuide",
                title="Gu\u00EDa: Histograma de residuos"))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualNormalCurvePlot",
                title="Distribuci\u00F3n observada de residuos vs curva normal te\u00F3rica",
                width=560,
                height=315,
                renderFun=".plotResidualNormalCurve"))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualNormalCurveGuide",
                title="Gu\u00EDa: Distribuci\u00F3n observada vs normal te\u00F3rica"))
            self$add(jmvcore::Html$new(
                options=options,
                name="varianceGuide",
                title="Homogeneidad de varianzas"))
            self$add(jmvcore::Table$new(
                options=options,
                name="varianceTests",
                title="Homogeneidad de varianzas entre grupos",
                columns=list(
                    list(
                        `name`="family", 
                        `title`="Familia", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Prueba", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="varianceInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Html$new(
                options=options,
                name="slopesGuide",
                title="Homogeneidad de pendientes",
                visible="(covs)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="slopesTests",
                title="Homogeneidad de pendientes en ANCOVA",
                visible="(covs)",
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text"),
                    list(
                        `name`="covariate", 
                        `title`="Covariable", 
                        `type`="text"),
                    list(
                        `name`="interaction", 
                        `title`="Interacci\u00F3n", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="slopesInterpretation",
                title="Interpretaci\u00F3n Aplicada",
                visible="(covs)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="covariateLinearityGuide",
                title="Linealidad de covariables",
                visible="(covs)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="covariateLinearity",
                title="Linealidad de covariables",
                visible="(covs)",
                columns=list(
                    list(
                        `name`="covariate", 
                        `title`="Covariable", 
                        `type`="text"),
                    list(
                        `name`="dependent", 
                        `title`="Variable dependiente", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Prueba / criterio", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="covariateLinearityInterpretation",
                title="Interpretaci\u00F3n Aplicada",
                visible="(covs)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="multicollinearityGuide",
                title="Multicolinealidad",
                visible="(covs)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="multicollinearity",
                title="Multicolinealidad",
                visible="(covs)",
                columns=list(
                    list(
                        `name`="diagnostic", 
                        `title`="Diagn\u00F3stico", 
                        `type`="text"),
                    list(
                        `name`="item", 
                        `title`="Elemento", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="multicollinearityInterpretation",
                title="Interpretaci\u00F3n Aplicada",
                visible="(covs)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationMatrixGuide",
                title="Matriz de correlaciones",
                visible="(covs)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="pearsonMatrixTable",
                title="Matriz de correlaciones de Pearson (formato APA 7)",
                visible="(covs)",
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dcorMatrixTable",
                title="Matriz de correlaci\u00F3n de distancia (dCor, formato APA 7)",
                visible="(covs)",
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationMatrixNote",
                title=" ",
                visible="(covs)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationComparisonGuide",
                title="An\u00E1lisis de discordancia Pearson / dCor / entrop\u00EDa copular",
                visible="(covs)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="correlationComparisonTable",
                title="Pares con diferencia notable entre Pearson y dCor",
                visible="(covs)",
                rows=0,
                columns=list(
                    list(
                        `name`="var1", 
                        `title`="Variable 1", 
                        `type`="text"),
                    list(
                        `name`="var2", 
                        `title`="Variable 2", 
                        `type`="text"),
                    list(
                        `name`="pearson", 
                        `title`="Pearson r", 
                        `type`="text"),
                    list(
                        `name`="dcor", 
                        `title`="dCor", 
                        `type`="text"),
                    list(
                        `name`="gap", 
                        `title`="Brecha (dCor \u2212 |r|)", 
                        `type`="number"),
                    list(
                        `name`="ce", 
                        `title`="Entrop\u00EDa copular", 
                        `type`="number"),
                    list(
                        `name`="ceP", 
                        `title`="p (CE)", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="ceSig", 
                        `title`="Sig. (CE)", 
                        `type`="text"),
                    list(
                        `name`="flag", 
                        `title`="Diferencia notable", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationComparisonInterpretation",
                title="Interpretaci\u00F3n Aplicada",
                visible="(covs)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="influenceGuide",
                title="Casos at\u00EDpicos e influyentes"))
            self$add(jmvcore::Table$new(
                options=options,
                name="influence",
                title="Casos at\u00EDpicos e influyentes",
                columns=list(
                    list(
                        `name`="case", 
                        `title`="Caso", 
                        `type`="integer"),
                    list(
                        `name`="fitted", 
                        `title`="Ajustado", 
                        `type`="number"),
                    list(
                        `name`="residual", 
                        `title`="Residuo", 
                        `type`="number"),
                    list(
                        `name`="studResidual", 
                        `title`="Residuo studentizado", 
                        `type`="number"),
                    list(
                        `name`="leverage", 
                        `title`="Leverage", 
                        `type`="number"),
                    list(
                        `name`="cooksD", 
                        `title`="Cook's D", 
                        `type`="number"),
                    list(
                        `name`="dffits", 
                        `title`="DFFITS", 
                        `type`="number"),
                    list(
                        `name`="criteria", 
                        `title`="Criterios activados", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="influenceInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualsLeveragePlot",
                title="Residuos studentizados vs leverage",
                width=600,
                height=350,
                renderFun=".plotResidualsLeverage"))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualsLeverageGuide",
                title="Gu\u00EDa: Residuos studentizados vs leverage"))
            self$add(jmvcore::Image$new(
                options=options,
                name="cooksDPlot",
                title="Cook's D por caso",
                width=560,
                height=300,
                renderFun=".plotCooksD"))
            self$add(jmvcore::Html$new(
                options=options,
                name="cooksDGuide",
                title="Gu\u00EDa: Cook's D por caso"))
            self$add(jmvcore::Html$new(
                options=options,
                name="independenceGuide",
                title="Independencia del dise\u00F1o"))
            self$add(jmvcore::Html$new(
                options=options,
                name="alternativesGuide",
                title="Alternativas metodol\u00F3gicas"))
            self$add(jmvcore::Table$new(
                options=options,
                name="alternatives",
                title="Alternativas metodol\u00F3gicas",
                columns=list(
                    list(
                        `name`="problem", 
                        `title`="Problema detectado", 
                        `type`="text"),
                    list(
                        `name`="evidence", 
                        `title`="Evidencia", 
                        `type`="text"),
                    list(
                        `name`="suggestion", 
                        `title`="Opci\u00F3n sugerida", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="alternativesWhen",
                title=""))
            self$add(jmvcore::Html$new(
                options=options,
                name="notes",
                title="Notas y recomendaci\u00F3n"))}))

anovaCheckBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovaCheckBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "AssumptionsLab",
                name = "anovaCheck",
                version = c(1,0,0),
                options = options,
                results = anovaCheckResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' ANOVA/ANCOVA
#'
#' 
#' @param data .
#' @param dep .
#' @param covs .
#' @param factors .
#' @param reportLang .
#' @param showPlots .
#' @param plotSet .
#' @param residSmoother .
#' @param residShowBand .
#' @param residRefLine .
#' @param influenceLabelMode .
#' @param influenceShowThreshold .
#' @param plotStyle .
#' @param plotPalette .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$designGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$designSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cellSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$designInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$diagnosticPlotsGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$groupBoxplotsPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$groupBoxplotsGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualNormalityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualNormality} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$residualNormalityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualsFittedPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$residualsFittedGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$qqResidualsPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$qqResidualsGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualHistogramPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$residualHistogramGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualNormalCurvePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$residualNormalCurveGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$varianceGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$varianceTests} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$varianceInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$slopesGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$slopesTests} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$slopesInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$covariateLinearityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$covariateLinearity} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$covariateLinearityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$multicollinearityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$multicollinearity} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$multicollinearityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationMatrixGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pearsonMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dcorMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$correlationMatrixNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationComparisonGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationComparisonTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$correlationComparisonInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$influenceGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$influence} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$influenceInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualsLeveragePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$residualsLeverageGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$cooksDPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cooksDGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$independenceGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$alternativesGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$alternatives} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$alternativesWhen} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$designSummary$asDF}
#'
#' \code{as.data.frame(results$designSummary)}
#'
#' @export
anovaCheck <- function(
    data,
    dep,
    covs = NULL,
    factors = NULL,
    reportLang = "en",
    showPlots = TRUE,
    plotSet = "complete",
    residSmoother = "none",
    residShowBand = FALSE,
    residRefLine = TRUE,
    influenceLabelMode = "top5",
    influenceShowThreshold = TRUE,
    plotStyle = "clean",
    plotPalette = "blueOrange") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("anovaCheck requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(factors), factors, NULL))

    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- anovaCheckOptions$new(
        dep = dep,
        covs = covs,
        factors = factors,
        reportLang = reportLang,
        showPlots = showPlots,
        plotSet = plotSet,
        residSmoother = residSmoother,
        residShowBand = residShowBand,
        residRefLine = residRefLine,
        influenceLabelMode = influenceLabelMode,
        influenceShowThreshold = influenceShowThreshold,
        plotStyle = plotStyle,
        plotPalette = plotPalette)

    analysis <- anovaCheckClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

