
# This file is automatically generated, you probably don't want to edit this

assumptionLibraryOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "assumptionLibraryOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            category = "all",
            reportLang = "en", ...) {

            super$initialize(
                package="AssumptionsLab",
                name="assumptionLibrary",
                requiresData=TRUE,
                ...)

            private$..category <- jmvcore::OptionList$new(
                "category",
                category,
                options=list(
                    "all",
                    "normality",
                    "homoscedasticity",
                    "linearity",
                    "independence",
                    "multicollinearity",
                    "influence",
                    "sphericity",
                    "proportionalOdds",
                    "robust"),
                default="all")
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"),
                default="en")

            self$.addOption(private$..category)
            self$.addOption(private$..reportLang)
        }),
    active = list(
        category = function() private$..category$value,
        reportLang = function() private$..reportLang$value),
    private = list(
        ..category = NA,
        ..reportLang = NA)
)

assumptionLibraryResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "assumptionLibraryResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        normality = function() private$.items[["normality"]],
        homoscedasticity = function() private$.items[["homoscedasticity"]],
        linearity = function() private$.items[["linearity"]],
        independence = function() private$.items[["independence"]],
        multicollinearity = function() private$.items[["multicollinearity"]],
        influence = function() private$.items[["influence"]],
        sphericity = function() private$.items[["sphericity"]],
        proportionalOdds = function() private$.items[["proportionalOdds"]],
        robust = function() private$.items[["robust"]],
        notes = function() private$.items[["notes"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Biblioteca de Supuestos")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Biblioteca de Supuestos"))
            self$add(jmvcore::Html$new(
                options=options,
                name="normality",
                title="Normalidad"))
            self$add(jmvcore::Html$new(
                options=options,
                name="homoscedasticity",
                title="Homocedasticidad / Homogeneidad de varianzas"))
            self$add(jmvcore::Html$new(
                options=options,
                name="linearity",
                title="Linealidad"))
            self$add(jmvcore::Html$new(
                options=options,
                name="independence",
                title="Independencia"))
            self$add(jmvcore::Html$new(
                options=options,
                name="multicollinearity",
                title="Multicolinealidad"))
            self$add(jmvcore::Html$new(
                options=options,
                name="influence",
                title="Casos at\u00EDpicos e influencia"))
            self$add(jmvcore::Html$new(
                options=options,
                name="sphericity",
                title="Esfericidad"))
            self$add(jmvcore::Html$new(
                options=options,
                name="proportionalOdds",
                title="Momios Proporcionales"))
            self$add(jmvcore::Html$new(
                options=options,
                name="robust",
                title="Transformaciones y alternativas robustas"))
            self$add(jmvcore::Html$new(
                options=options,
                name="notes",
                title="Uso de esta biblioteca"))}))

assumptionLibraryBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "assumptionLibraryBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "AssumptionsLab",
                name = "assumptionLibrary",
                version = c(1,0,0),
                options = options,
                results = assumptionLibraryResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Assumption Library
#'
#' 
#' @param data .
#' @param category .
#' @param reportLang .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$normality} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$homoscedasticity} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$linearity} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$independence} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$multicollinearity} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$influence} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$sphericity} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$proportionalOdds} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$robust} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
assumptionLibrary <- function(
    data,
    category = "all",
    reportLang = "en") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("assumptionLibrary requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- assumptionLibraryOptions$new(
        category = category,
        reportLang = reportLang)

    analysis <- assumptionLibraryClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

