
# This file is automatically generated, you probably don't want to edit this

assumptionLibraryOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "assumptionLibraryOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            category = "all",
            reportLang = "en", ...) {

            super$initialize(
                package="AssumptionsLab",
                name="assumptionLibrary",
                requiresData=TRUE,
                ...)

            private$..category <- jmvcore::OptionList$new(
                "category",
                category,
                options=list(
                    "all",
                    "normality",
                    "homoscedasticity",
                    "linearity",
                    "independence",
                    "multicollinearity",
                    "influence",
                    "sphericity",
                    "proportionalOdds",
                    "independenceIrrelevantAlternatives",
                    "robust"),
                default="all")
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"),
                default="en")

            self$.addOption(private$..category)
            self$.addOption(private$..reportLang)
        }),
    active = list(
        category = function() private$..category$value,
        reportLang = function() private$..reportLang$value),
    private = list(
        ..category = NA,
        ..reportLang = NA)
)

assumptionLibraryResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "assumptionLibraryResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        normality = function() private$.items[["normality"]],
        homoscedasticity = function() private$.items[["homoscedasticity"]],
        linearity = function() private$.items[["linearity"]],
        independence = function() private$.items[["independence"]],
        multicollinearity = function() private$.items[["multicollinearity"]],
        influence = function() private$.items[["influence"]],
        sphericity = function() private$.items[["sphericity"]],
        proportionalOdds = function() private$.items[["proportionalOdds"]],
        independenceIrrelevantAlternatives = function() private$.items[["independenceIrrelevantAlternatives"]],
        robust = function() private$.items[["robust"]],
        notes = function() private$.items[["notes"]],
        totalBibliography = function() private$.items[["totalBibliography"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Assumption Library")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Assumption Library"))
            self$add(jmvcore::Html$new(
                options=options,
                name="normality",
                title="Normality",
                refs=list(
                    "shapiro_1965",
                    "lilliefors_1967",
                    "anderson_1952",
                    "shapiro_1972",
                    "jarque_1987",
                    "razali_2011")))
            self$add(jmvcore::Html$new(
                options=options,
                name="homoscedasticity",
                title="Homoscedasticity / Homogeneity of variances",
                refs=list(
                    "levene_1960",
                    "brown_1974",
                    "bartlett_1937",
                    "fligner_1976",
                    "hartley_1950",
                    "breusch_1979",
                    "white_1980",
                    "goldfeld_1965",
                    "mackinnon_1985",
                    "welch_1947")))
            self$add(jmvcore::Html$new(
                options=options,
                name="linearity",
                title="Linearity",
                refs=list(
                    "box_1962",
                    "ramsey_1969",
                    "sz_kely_2007",
                    "ma_2011")))
            self$add(jmvcore::Html$new(
                options=options,
                name="independence",
                title="Independence",
                refs=list(
                    "durbin_1951",
                    "breusch_1978",
                    "godfrey_1978",
                    "ljung_1978")))
            self$add(jmvcore::Html$new(
                options=options,
                name="multicollinearity",
                title="Multicollinearity",
                refs=list(
                    "marquardt_1970",
                    "belsley_1980",
                    "o_brien_2007")))
            self$add(jmvcore::Html$new(
                options=options,
                name="influence",
                title="Outliers and influence",
                refs=list(
                    "cook_1977",
                    "mahalanobis_1936",
                    "belsley_1980")))
            self$add(jmvcore::Html$new(
                options=options,
                name="sphericity",
                title="Sphericity",
                refs=list(
                    "mauchly_1940",
                    "greenhouse_1959",
                    "huynh_1976",
                    "friedman_1937")))
            self$add(jmvcore::Html$new(
                options=options,
                name="proportionalOdds",
                title="Proportional Odds",
                refs=list(
                    "brant_1990")))
            self$add(jmvcore::Html$new(
                options=options,
                name="independenceIrrelevantAlternatives",
                title="Independence of Irrelevant Alternatives",
                refs=list(
                    "hausman_1984",
                    "cheng_2007")))
            self$add(jmvcore::Html$new(
                options=options,
                name="robust",
                title="Transformations and robust alternatives",
                refs=list(
                    "friedman_1937",
                    "mackinnon_1985",
                    "welch_1947",
                    "wilcoxon_1945")))
            self$add(jmvcore::Html$new(
                options=options,
                name="notes",
                title="Using this library"))
            self$add(jmvcore::Html$new(
                options=options,
                name="totalBibliography",
                title="Complete Bibliography (All Categories)",
                refs=list(
                    "shapiro_1965",
                    "lilliefors_1967",
                    "anderson_1952",
                    "shapiro_1972",
                    "jarque_1987",
                    "razali_2011",
                    "levene_1960",
                    "brown_1974",
                    "bartlett_1937",
                    "fligner_1976",
                    "hartley_1950",
                    "breusch_1979",
                    "white_1980",
                    "goldfeld_1965",
                    "mackinnon_1985",
                    "welch_1947",
                    "box_1962",
                    "ramsey_1969",
                    "sz_kely_2007",
                    "ma_2011",
                    "durbin_1951",
                    "breusch_1978",
                    "godfrey_1978",
                    "ljung_1978",
                    "marquardt_1970",
                    "belsley_1980",
                    "o_brien_2007",
                    "cook_1977",
                    "mahalanobis_1936",
                    "mauchly_1940",
                    "greenhouse_1959",
                    "huynh_1976",
                    "friedman_1937",
                    "brant_1990",
                    "hausman_1984",
                    "cheng_2007",
                    "wilcoxon_1945")))}))

assumptionLibraryBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "assumptionLibraryBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "AssumptionsLab",
                name = "assumptionLibrary",
                version = c(1,0,0),
                options = options,
                results = assumptionLibraryResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Assumption Library
#'
#' 
#' @param data .
#' @param category .
#' @param reportLang .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$normality} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$homoscedasticity} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$linearity} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$independence} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$multicollinearity} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$influence} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$sphericity} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$proportionalOdds} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$independenceIrrelevantAlternatives} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$robust} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$totalBibliography} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
assumptionLibrary <- function(
    data,
    category = "all",
    reportLang = "en") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("assumptionLibrary requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- assumptionLibraryOptions$new(
        category = category,
        reportLang = reportLang)

    analysis <- assumptionLibraryClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

