
# This file is automatically generated, you probably don't want to edit this

bibliographyOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bibliographyOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            topic = "all",
            reportLang = "en", ...) {

            super$initialize(
                package="AssumptionsLab",
                name="bibliography",
                requiresData=TRUE,
                ...)

            private$..topic <- jmvcore::OptionList$new(
                "topic",
                topic,
                options=list(
                    "all",
                    "assumptions",
                    "normality",
                    "homoscedasticity",
                    "regression",
                    "path",
                    "related",
                    "time_series",
                    "robust"),
                default="all")
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"),
                default="en")

            self$.addOption(private$..topic)
            self$.addOption(private$..reportLang)
        }),
    active = list(
        topic = function() private$..topic$value,
        reportLang = function() private$..reportLang$value),
    private = list(
        ..topic = NA,
        ..reportLang = NA)
)

bibliographyResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bibliographyResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        references = function() private$.items[["references"]],
        notes = function() private$.items[["notes"]],
        citationsTable = function() private$.items[["citationsTable"]],
        biblioSummary = function() private$.items[["biblioSummary"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bibliografía")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Bibliograf\u00EDa"))
            self$add(jmvcore::Html$new(
                options=options,
                name="references",
                title="Referencias en formato APA 7.\u00AA edici\u00F3n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="notes",
                title="Notes / Notas"))
            self$add(jmvcore::Html$new(
                options=options,
                name="citationsTable",
                title="Citations / Citaciones"))
            self$add(jmvcore::Html$new(
                options=options,
                name="biblioSummary",
                title="Bibliometric Summary / Resumen bibliom\u00E9trico"))}))

bibliographyBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bibliographyBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "AssumptionsLab",
                name = "bibliography",
                version = c(1,0,0),
                options = options,
                results = bibliographyResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bibliography
#'
#' 
#' @param data .
#' @param topic .
#' @param reportLang .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$references} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$citationsTable} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$biblioSummary} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
bibliography <- function(
    data,
    topic = "all",
    reportLang = "en") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bibliography requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- bibliographyOptions$new(
        topic = topic,
        reportLang = reportLang)

    analysis <- bibliographyClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

