
# This file is automatically generated, you probably don't want to edit this

logCheckOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "logCheckOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            factors = NULL,
            reportLang = "en",
            showPlots = TRUE,
            linShowPlots = TRUE,
            linSmoother = "none",
            linBins = 8,
            caliShowPlots = TRUE,
            caliBins = 10,
            caliRefLine = TRUE,
            rocShowPlots = TRUE,
            rocRefLine = TRUE,
            rocShowAUCLabel = TRUE,
            influenceShowPlots = TRUE,
            influenceLabelMode = "top5",
            influenceShowThreshold = TRUE,
            plotStyle = "clean",
            plotPalette = "blueOrange", ...) {

            super$initialize(
                package="AssumptionsLab",
                name="logCheck",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"),
                default="en")
            private$..showPlots <- jmvcore::OptionBool$new(
                "showPlots",
                showPlots,
                default=TRUE)
            private$..linShowPlots <- jmvcore::OptionBool$new(
                "linShowPlots",
                linShowPlots,
                default=TRUE)
            private$..linSmoother <- jmvcore::OptionList$new(
                "linSmoother",
                linSmoother,
                options=list(
                    "none",
                    "linear",
                    "loess"),
                default="none")
            private$..linBins <- jmvcore::OptionNumber$new(
                "linBins",
                linBins,
                min=4,
                max=20,
                default=8)
            private$..caliShowPlots <- jmvcore::OptionBool$new(
                "caliShowPlots",
                caliShowPlots,
                default=TRUE)
            private$..caliBins <- jmvcore::OptionNumber$new(
                "caliBins",
                caliBins,
                min=4,
                max=20,
                default=10)
            private$..caliRefLine <- jmvcore::OptionBool$new(
                "caliRefLine",
                caliRefLine,
                default=TRUE)
            private$..rocShowPlots <- jmvcore::OptionBool$new(
                "rocShowPlots",
                rocShowPlots,
                default=TRUE)
            private$..rocRefLine <- jmvcore::OptionBool$new(
                "rocRefLine",
                rocRefLine,
                default=TRUE)
            private$..rocShowAUCLabel <- jmvcore::OptionBool$new(
                "rocShowAUCLabel",
                rocShowAUCLabel,
                default=TRUE)
            private$..influenceShowPlots <- jmvcore::OptionBool$new(
                "influenceShowPlots",
                influenceShowPlots,
                default=TRUE)
            private$..influenceLabelMode <- jmvcore::OptionList$new(
                "influenceLabelMode",
                influenceLabelMode,
                options=list(
                    "none",
                    "cooks",
                    "leverage",
                    "studres",
                    "top5"),
                default="top5")
            private$..influenceShowThreshold <- jmvcore::OptionBool$new(
                "influenceShowThreshold",
                influenceShowThreshold,
                default=TRUE)
            private$..plotStyle <- jmvcore::OptionList$new(
                "plotStyle",
                plotStyle,
                options=list(
                    "clean",
                    "bw",
                    "contrast",
                    "fullColor"),
                default="clean")
            private$..plotPalette <- jmvcore::OptionList$new(
                "plotPalette",
                plotPalette,
                options=list(
                    "blueOrange",
                    "viridis",
                    "greyscale",
                    "colorblind"),
                default="blueOrange")

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..factors)
            self$.addOption(private$..reportLang)
            self$.addOption(private$..showPlots)
            self$.addOption(private$..linShowPlots)
            self$.addOption(private$..linSmoother)
            self$.addOption(private$..linBins)
            self$.addOption(private$..caliShowPlots)
            self$.addOption(private$..caliBins)
            self$.addOption(private$..caliRefLine)
            self$.addOption(private$..rocShowPlots)
            self$.addOption(private$..rocRefLine)
            self$.addOption(private$..rocShowAUCLabel)
            self$.addOption(private$..influenceShowPlots)
            self$.addOption(private$..influenceLabelMode)
            self$.addOption(private$..influenceShowThreshold)
            self$.addOption(private$..plotStyle)
            self$.addOption(private$..plotPalette)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        factors = function() private$..factors$value,
        reportLang = function() private$..reportLang$value,
        showPlots = function() private$..showPlots$value,
        linShowPlots = function() private$..linShowPlots$value,
        linSmoother = function() private$..linSmoother$value,
        linBins = function() private$..linBins$value,
        caliShowPlots = function() private$..caliShowPlots$value,
        caliBins = function() private$..caliBins$value,
        caliRefLine = function() private$..caliRefLine$value,
        rocShowPlots = function() private$..rocShowPlots$value,
        rocRefLine = function() private$..rocRefLine$value,
        rocShowAUCLabel = function() private$..rocShowAUCLabel$value,
        influenceShowPlots = function() private$..influenceShowPlots$value,
        influenceLabelMode = function() private$..influenceLabelMode$value,
        influenceShowThreshold = function() private$..influenceShowThreshold$value,
        plotStyle = function() private$..plotStyle$value,
        plotPalette = function() private$..plotPalette$value),
    private = list(
        ..dep = NA,
        ..covs = NA,
        ..factors = NA,
        ..reportLang = NA,
        ..showPlots = NA,
        ..linShowPlots = NA,
        ..linSmoother = NA,
        ..linBins = NA,
        ..caliShowPlots = NA,
        ..caliBins = NA,
        ..caliRefLine = NA,
        ..rocShowPlots = NA,
        ..rocRefLine = NA,
        ..rocShowAUCLabel = NA,
        ..influenceShowPlots = NA,
        ..influenceLabelMode = NA,
        ..influenceShowThreshold = NA,
        ..plotStyle = NA,
        ..plotPalette = NA)
)

logCheckResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "logCheckResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        designGuide = function() private$.items[["designGuide"]],
        design = function() private$.items[["design"]],
        separationGuide = function() private$.items[["separationGuide"]],
        separation = function() private$.items[["separation"]],
        separationInterpretation = function() private$.items[["separationInterpretation"]],
        linearityGuide = function() private$.items[["linearityGuide"]],
        linearity = function() private$.items[["linearity"]],
        linearityInterpretation = function() private$.items[["linearityInterpretation"]],
        linearityPlot = function() private$.items[["linearityPlot"]],
        goodnessOfFitGuide = function() private$.items[["goodnessOfFitGuide"]],
        goodnessOfFit = function() private$.items[["goodnessOfFit"]],
        goodnessOfFitInterpretation = function() private$.items[["goodnessOfFitInterpretation"]],
        calibrationPlot = function() private$.items[["calibrationPlot"]],
        discriminationGuide = function() private$.items[["discriminationGuide"]],
        discrimination = function() private$.items[["discrimination"]],
        discriminationInterpretation = function() private$.items[["discriminationInterpretation"]],
        discriminationPlot = function() private$.items[["discriminationPlot"]],
        multicollinearityGuide = function() private$.items[["multicollinearityGuide"]],
        multicollinearity = function() private$.items[["multicollinearity"]],
        multicollinearityInterpretation = function() private$.items[["multicollinearityInterpretation"]],
        correlationMatrixGuide = function() private$.items[["correlationMatrixGuide"]],
        pearsonMatrixTable = function() private$.items[["pearsonMatrixTable"]],
        dcorMatrixTable = function() private$.items[["dcorMatrixTable"]],
        correlationMatrixNote = function() private$.items[["correlationMatrixNote"]],
        correlationComparisonGuide = function() private$.items[["correlationComparisonGuide"]],
        correlationComparisonTable = function() private$.items[["correlationComparisonTable"]],
        correlationComparisonInterpretation = function() private$.items[["correlationComparisonInterpretation"]],
        influenceGuide = function() private$.items[["influenceGuide"]],
        influence = function() private$.items[["influence"]],
        influenceInterpretation = function() private$.items[["influenceInterpretation"]],
        influencePlot = function() private$.items[["influencePlot"]],
        oddsRatiosGuide = function() private$.items[["oddsRatiosGuide"]],
        oddsRatios = function() private$.items[["oddsRatios"]],
        oddsRatiosInterpretation = function() private$.items[["oddsRatiosInterpretation"]],
        notes = function() private$.items[["notes"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Regresión logística")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introducci\u00F3n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="designGuide",
                title="Dise\u00F1o del modelo"))
            self$add(jmvcore::Table$new(
                options=options,
                name="design",
                title="Resumen del dise\u00F1o",
                columns=list(
                    list(
                        `name`="element", 
                        `title`="Elemento", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="separationGuide",
                title="Separaci\u00F3n completa"))
            self$add(jmvcore::Table$new(
                options=options,
                name="separation",
                title="Separaci\u00F3n completa",
                columns=list(
                    list(
                        `name`="predictor", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="type", 
                        `title`="Tipo", 
                        `type`="text"),
                    list(
                        `name`="coefficient", 
                        `title`="Coeficiente", 
                        `type`="number", 
                        `format`="decimal"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="separationInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Html$new(
                options=options,
                name="linearityGuide",
                title="Linealidad en el logit"))
            self$add(jmvcore::Table$new(
                options=options,
                name="linearity",
                title="Linealidad en el logit (Box-Tidwell)",
                columns=list(
                    list(
                        `name`="predictor", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="number", 
                        `format`="decimal"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="linearityInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Image$new(
                options=options,
                name="linearityPlot",
                title="Logit emp\u00EDrico vs predictor",
                requiresData=TRUE,
                width=560,
                height=340,
                renderFun=".plotLinearity",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "plotStyle",
                    "plotPalette",
                    "linSmoother",
                    "linBins",
                    "reportLang")))
            self$add(jmvcore::Html$new(
                options=options,
                name="goodnessOfFitGuide",
                title="Bondad de ajuste"))
            self$add(jmvcore::Table$new(
                options=options,
                name="goodnessOfFit",
                title="Bondad de ajuste",
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Prueba", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="number", 
                        `format`="decimal"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="goodnessOfFitInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Image$new(
                options=options,
                name="calibrationPlot",
                title="Calibraci\u00F3n por deciles de probabilidad",
                requiresData=TRUE,
                width=560,
                height=340,
                renderFun=".plotCalibration",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "plotStyle",
                    "plotPalette",
                    "caliBins",
                    "caliRefLine",
                    "reportLang")))
            self$add(jmvcore::Html$new(
                options=options,
                name="discriminationGuide",
                title="Discriminaci\u00F3n"))
            self$add(jmvcore::Table$new(
                options=options,
                name="discrimination",
                title="Discriminaci\u00F3n",
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="M\u00E9trica", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number", 
                        `format`="decimal"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="discriminationInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Image$new(
                options=options,
                name="discriminationPlot",
                title="Curva ROC",
                requiresData=TRUE,
                width=460,
                height=460,
                renderFun=".plotROC",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "plotStyle",
                    "plotPalette",
                    "rocRefLine",
                    "rocShowAUCLabel",
                    "reportLang")))
            self$add(jmvcore::Html$new(
                options=options,
                name="multicollinearityGuide",
                title="Multicolinealidad",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="multicollinearity",
                title="Multicolinealidad",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="diagnostic", 
                        `title`="Diagn\u00F3stico", 
                        `type`="text"),
                    list(
                        `name`="item", 
                        `title`="Elemento", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="multicollinearityInterpretation",
                title="Interpretaci\u00F3n Aplicada",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationMatrixGuide",
                title="Matriz de correlaciones",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="pearsonMatrixTable",
                title="Matriz de correlaciones de Pearson (formato APA 7)",
                rows=0,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dcorMatrixTable",
                title="Matriz de correlaci\u00F3n de distancia (dCor, formato APA 7)",
                rows=0,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationMatrixNote",
                title=" ",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationComparisonGuide",
                title="An\u00E1lisis de discordancia Pearson / dCor / entrop\u00EDa copular",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="correlationComparisonTable",
                title="Pares con diferencia notable entre Pearson y dCor",
                rows=0,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="var1", 
                        `title`="Variable 1", 
                        `type`="text"),
                    list(
                        `name`="var2", 
                        `title`="Variable 2", 
                        `type`="text"),
                    list(
                        `name`="pearson", 
                        `title`="Pearson r", 
                        `type`="text"),
                    list(
                        `name`="dcor", 
                        `title`="dCor", 
                        `type`="text"),
                    list(
                        `name`="gap", 
                        `title`="Brecha (dCor \u2212 |r|)", 
                        `type`="number"),
                    list(
                        `name`="ce", 
                        `title`="Entrop\u00EDa copular", 
                        `type`="number"),
                    list(
                        `name`="ceP", 
                        `title`="p (CE)", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="ceSig", 
                        `title`="Sig. (CE)", 
                        `type`="text"),
                    list(
                        `name`="flag", 
                        `title`="Diferencia notable", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationComparisonInterpretation",
                title="Interpretaci\u00F3n Aplicada",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="influenceGuide",
                title="Casos influyentes"))
            self$add(jmvcore::Table$new(
                options=options,
                name="influence",
                title="Casos influyentes",
                columns=list(
                    list(
                        `name`="case", 
                        `title`="Caso", 
                        `type`="integer"),
                    list(
                        `name`="cooksD", 
                        `title`="Cook's D", 
                        `type`="number", 
                        `format`="decimal"),
                    list(
                        `name`="leverage", 
                        `title`="Leverage", 
                        `type`="number", 
                        `format`="decimal"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="influenceInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Image$new(
                options=options,
                name="influencePlot",
                title="Cook's D por caso",
                requiresData=TRUE,
                width=560,
                height=320,
                renderFun=".plotInfluence",
                clearWith=list(
                    "dep",
                    "covs",
                    "factors",
                    "plotStyle",
                    "plotPalette",
                    "influenceLabelMode",
                    "influenceShowThreshold",
                    "reportLang")))
            self$add(jmvcore::Html$new(
                options=options,
                name="oddsRatiosGuide",
                title="Odds Ratios"))
            self$add(jmvcore::Table$new(
                options=options,
                name="oddsRatios",
                title="Odds Ratios",
                columns=list(
                    list(
                        `name`="predictor", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="or", 
                        `title`="OR", 
                        `type`="number", 
                        `format`="decimal"),
                    list(
                        `name`="ciLower", 
                        `title`="IC 95% inferior", 
                        `type`="number", 
                        `format`="decimal"),
                    list(
                        `name`="ciUpper", 
                        `title`="IC 95% superior", 
                        `type`="number", 
                        `format`="decimal"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="oddsRatiosInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Html$new(
                options=options,
                name="notes",
                title="Notas y recomendaci\u00F3n"))}))

logCheckBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "logCheckBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "AssumptionsLab",
                name = "logCheck",
                version = c(1,0,0),
                options = options,
                results = logCheckResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Logistic Regression
#'
#' 
#' @param data .
#' @param dep .
#' @param covs .
#' @param factors .
#' @param reportLang .
#' @param showPlots .
#' @param linShowPlots .
#' @param linSmoother .
#' @param linBins .
#' @param caliShowPlots .
#' @param caliBins .
#' @param caliRefLine .
#' @param rocShowPlots .
#' @param rocRefLine .
#' @param rocShowAUCLabel .
#' @param influenceShowPlots .
#' @param influenceLabelMode .
#' @param influenceShowThreshold .
#' @param plotStyle .
#' @param plotPalette .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$designGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$design} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$separationGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$separation} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$separationInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$linearityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$linearity} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$linearityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$linearityPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$goodnessOfFitGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$goodnessOfFit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$goodnessOfFitInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$calibrationPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$discriminationGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$discrimination} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$discriminationInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$discriminationPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$multicollinearityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$multicollinearity} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$multicollinearityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationMatrixGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pearsonMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dcorMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$correlationMatrixNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationComparisonGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationComparisonTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$correlationComparisonInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$influenceGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$influence} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$influenceInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$influencePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$oddsRatiosGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$oddsRatios} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$oddsRatiosInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$design$asDF}
#'
#' \code{as.data.frame(results$design)}
#'
#' @export
logCheck <- function(
    data,
    dep,
    covs = NULL,
    factors = NULL,
    reportLang = "en",
    showPlots = TRUE,
    linShowPlots = TRUE,
    linSmoother = "none",
    linBins = 8,
    caliShowPlots = TRUE,
    caliBins = 10,
    caliRefLine = TRUE,
    rocShowPlots = TRUE,
    rocRefLine = TRUE,
    rocShowAUCLabel = TRUE,
    influenceShowPlots = TRUE,
    influenceLabelMode = "top5",
    influenceShowThreshold = TRUE,
    plotStyle = "clean",
    plotPalette = "blueOrange") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("logCheck requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(factors), factors, NULL))

    for (v in dep) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- logCheckOptions$new(
        dep = dep,
        covs = covs,
        factors = factors,
        reportLang = reportLang,
        showPlots = showPlots,
        linShowPlots = linShowPlots,
        linSmoother = linSmoother,
        linBins = linBins,
        caliShowPlots = caliShowPlots,
        caliBins = caliBins,
        caliRefLine = caliRefLine,
        rocShowPlots = rocShowPlots,
        rocRefLine = rocRefLine,
        rocShowAUCLabel = rocShowAUCLabel,
        influenceShowPlots = influenceShowPlots,
        influenceLabelMode = influenceLabelMode,
        influenceShowThreshold = influenceShowThreshold,
        plotStyle = plotStyle,
        plotPalette = plotPalette)

    analysis <- logCheckClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

