
# This file is automatically generated, you probably don't want to edit this

pathCheckOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pathCheckOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            relations = NULL,
            isFinalized = FALSE,
            showCoeffs = TRUE,
            showR2 = TRUE,
            showCorrs = FALSE,
            showCovs = FALSE,
            showResiduals = FALSE,
            showExogenous = TRUE,
            showEndogenous = TRUE,
            permutations = 999,
            permutationSeed = 2026,
            residBinMethod = "sturges",
            residShowNormalCurve = TRUE,
            residFlagOutliers = TRUE,
            plotPalette = "jamovi",
            reportLang = "en",
            showDiagram = TRUE,
            diagramEdgeLabel = "coef",
            diagramShowErrors = FALSE,
            diagramOffsetLabels = FALSE,
            diagramLayout = "hierarchical",
            diagramRotate = "exogLeft",
            diagramNodeSize = "medium",
            diagramShape = "ellipse",
            diagramAbbreviate = "none", ...) {

            super$initialize(
                package="AssumptionsLab",
                name="pathCheck",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..relations <- jmvcore::OptionPairs$new(
                "relations",
                relations,
                permitted=list(
                    "numeric"))
            private$..isFinalized <- jmvcore::OptionBool$new(
                "isFinalized",
                isFinalized,
                default=FALSE)
            private$..showCoeffs <- jmvcore::OptionBool$new(
                "showCoeffs",
                showCoeffs,
                default=TRUE)
            private$..showR2 <- jmvcore::OptionBool$new(
                "showR2",
                showR2,
                default=TRUE)
            private$..showCorrs <- jmvcore::OptionBool$new(
                "showCorrs",
                showCorrs,
                default=FALSE)
            private$..showCovs <- jmvcore::OptionBool$new(
                "showCovs",
                showCovs,
                default=FALSE)
            private$..showResiduals <- jmvcore::OptionBool$new(
                "showResiduals",
                showResiduals,
                default=FALSE)
            private$..showExogenous <- jmvcore::OptionBool$new(
                "showExogenous",
                showExogenous,
                default=TRUE)
            private$..showEndogenous <- jmvcore::OptionBool$new(
                "showEndogenous",
                showEndogenous,
                default=TRUE)
            private$..permutations <- jmvcore::OptionNumber$new(
                "permutations",
                permutations,
                default=999,
                min=199,
                max=9999)
            private$..permutationSeed <- jmvcore::OptionNumber$new(
                "permutationSeed",
                permutationSeed,
                default=2026,
                min=1,
                max=999999)
            private$..residBinMethod <- jmvcore::OptionList$new(
                "residBinMethod",
                residBinMethod,
                options=list(
                    "sturges",
                    "scott",
                    "fd"),
                default="sturges")
            private$..residShowNormalCurve <- jmvcore::OptionBool$new(
                "residShowNormalCurve",
                residShowNormalCurve,
                default=TRUE)
            private$..residFlagOutliers <- jmvcore::OptionBool$new(
                "residFlagOutliers",
                residFlagOutliers,
                default=TRUE)
            private$..plotPalette <- jmvcore::OptionList$new(
                "plotPalette",
                plotPalette,
                options=list(
                    "jamovi",
                    "colorblind",
                    "viridis"),
                default="jamovi")
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"),
                default="en")
            private$..showDiagram <- jmvcore::OptionBool$new(
                "showDiagram",
                showDiagram,
                default=TRUE)
            private$..diagramEdgeLabel <- jmvcore::OptionList$new(
                "diagramEdgeLabel",
                diagramEdgeLabel,
                options=list(
                    "coef",
                    "beta",
                    "labels",
                    "none"),
                default="coef")
            private$..diagramShowErrors <- jmvcore::OptionBool$new(
                "diagramShowErrors",
                diagramShowErrors,
                default=FALSE)
            private$..diagramOffsetLabels <- jmvcore::OptionBool$new(
                "diagramOffsetLabels",
                diagramOffsetLabels,
                default=FALSE)
            private$..diagramLayout <- jmvcore::OptionList$new(
                "diagramLayout",
                diagramLayout,
                options=list(
                    "hierarchical",
                    "circular",
                    "spring"),
                default="hierarchical")
            private$..diagramRotate <- jmvcore::OptionList$new(
                "diagramRotate",
                diagramRotate,
                options=list(
                    "exogLeft",
                    "exogTop",
                    "exogRight",
                    "exogBottom"),
                default="exogLeft")
            private$..diagramNodeSize <- jmvcore::OptionList$new(
                "diagramNodeSize",
                diagramNodeSize,
                options=list(
                    "small",
                    "medium",
                    "large"),
                default="medium")
            private$..diagramShape <- jmvcore::OptionList$new(
                "diagramShape",
                diagramShape,
                options=list(
                    "ellipse",
                    "rectangle",
                    "circle"),
                default="ellipse")
            private$..diagramAbbreviate <- jmvcore::OptionList$new(
                "diagramAbbreviate",
                diagramAbbreviate,
                options=list(
                    "none",
                    "abbrev8",
                    "abbrev4"),
                default="none")

            self$.addOption(private$..vars)
            self$.addOption(private$..relations)
            self$.addOption(private$..isFinalized)
            self$.addOption(private$..showCoeffs)
            self$.addOption(private$..showR2)
            self$.addOption(private$..showCorrs)
            self$.addOption(private$..showCovs)
            self$.addOption(private$..showResiduals)
            self$.addOption(private$..showExogenous)
            self$.addOption(private$..showEndogenous)
            self$.addOption(private$..permutations)
            self$.addOption(private$..permutationSeed)
            self$.addOption(private$..residBinMethod)
            self$.addOption(private$..residShowNormalCurve)
            self$.addOption(private$..residFlagOutliers)
            self$.addOption(private$..plotPalette)
            self$.addOption(private$..reportLang)
            self$.addOption(private$..showDiagram)
            self$.addOption(private$..diagramEdgeLabel)
            self$.addOption(private$..diagramShowErrors)
            self$.addOption(private$..diagramOffsetLabels)
            self$.addOption(private$..diagramLayout)
            self$.addOption(private$..diagramRotate)
            self$.addOption(private$..diagramNodeSize)
            self$.addOption(private$..diagramShape)
            self$.addOption(private$..diagramAbbreviate)
        }),
    active = list(
        vars = function() private$..vars$value,
        relations = function() private$..relations$value,
        isFinalized = function() private$..isFinalized$value,
        showCoeffs = function() private$..showCoeffs$value,
        showR2 = function() private$..showR2$value,
        showCorrs = function() private$..showCorrs$value,
        showCovs = function() private$..showCovs$value,
        showResiduals = function() private$..showResiduals$value,
        showExogenous = function() private$..showExogenous$value,
        showEndogenous = function() private$..showEndogenous$value,
        permutations = function() private$..permutations$value,
        permutationSeed = function() private$..permutationSeed$value,
        residBinMethod = function() private$..residBinMethod$value,
        residShowNormalCurve = function() private$..residShowNormalCurve$value,
        residFlagOutliers = function() private$..residFlagOutliers$value,
        plotPalette = function() private$..plotPalette$value,
        reportLang = function() private$..reportLang$value,
        showDiagram = function() private$..showDiagram$value,
        diagramEdgeLabel = function() private$..diagramEdgeLabel$value,
        diagramShowErrors = function() private$..diagramShowErrors$value,
        diagramOffsetLabels = function() private$..diagramOffsetLabels$value,
        diagramLayout = function() private$..diagramLayout$value,
        diagramRotate = function() private$..diagramRotate$value,
        diagramNodeSize = function() private$..diagramNodeSize$value,
        diagramShape = function() private$..diagramShape$value,
        diagramAbbreviate = function() private$..diagramAbbreviate$value),
    private = list(
        ..vars = NA,
        ..relations = NA,
        ..isFinalized = NA,
        ..showCoeffs = NA,
        ..showR2 = NA,
        ..showCorrs = NA,
        ..showCovs = NA,
        ..showResiduals = NA,
        ..showExogenous = NA,
        ..showEndogenous = NA,
        ..permutations = NA,
        ..permutationSeed = NA,
        ..residBinMethod = NA,
        ..residShowNormalCurve = NA,
        ..residFlagOutliers = NA,
        ..plotPalette = NA,
        ..reportLang = NA,
        ..showDiagram = NA,
        ..diagramEdgeLabel = NA,
        ..diagramShowErrors = NA,
        ..diagramOffsetLabels = NA,
        ..diagramLayout = NA,
        ..diagramRotate = NA,
        ..diagramNodeSize = NA,
        ..diagramShape = NA,
        ..diagramAbbreviate = NA)
)

pathCheckResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pathCheckResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        modelSummary = function() private$.items[["modelSummary"]],
        specifiedModel = function() private$.items[["specifiedModel"]],
        modelStructureGuide = function() private$.items[["modelStructureGuide"]],
        exogenousTable = function() private$.items[["exogenousTable"]],
        endogenousTable = function() private$.items[["endogenousTable"]],
        validationSummary = function() private$.items[["validationSummary"]],
        pathDiagram = function() private$.items[["pathDiagram"]],
        outlierGuide = function() private$.items[["outlierGuide"]],
        outlierTable = function() private$.items[["outlierTable"]],
        equationsGuide = function() private$.items[["equationsGuide"]],
        pathCoefficients = function() private$.items[["pathCoefficients"]],
        coefficientsInterpretation = function() private$.items[["coefficientsInterpretation"]],
        rSquaredTable = function() private$.items[["rSquaredTable"]],
        residualCovarianceGuide = function() private$.items[["residualCovarianceGuide"]],
        residualCovarianceTable = function() private$.items[["residualCovarianceTable"]],
        residualPlots = function() private$.items[["residualPlots"]],
        normalityGuide = function() private$.items[["normalityGuide"]],
        residualNormality = function() private$.items[["residualNormality"]],
        normalityInterpretation = function() private$.items[["normalityInterpretation"]],
        homoscedasticityGuide = function() private$.items[["homoscedasticityGuide"]],
        homoscedasticity = function() private$.items[["homoscedasticity"]],
        homoscedasticityInterpretation = function() private$.items[["homoscedasticityInterpretation"]],
        multicollinearityGuide = function() private$.items[["multicollinearityGuide"]],
        multicollinearity = function() private$.items[["multicollinearity"]],
        multicollinearityInterpretation = function() private$.items[["multicollinearityInterpretation"]],
        mardiaGuide = function() private$.items[["mardiaGuide"]],
        mardiaTable = function() private$.items[["mardiaTable"]],
        mardiaInterpretation = function() private$.items[["mardiaInterpretation"]],
        correlationMatrixGuide = function() private$.items[["correlationMatrixGuide"]],
        pearsonMatrixTable = function() private$.items[["pearsonMatrixTable"]],
        dcorMatrixTable = function() private$.items[["dcorMatrixTable"]],
        correlationMatrixNote = function() private$.items[["correlationMatrixNote"]],
        correlationComparisonGuide = function() private$.items[["correlationComparisonGuide"]],
        correlationComparisonTable = function() private$.items[["correlationComparisonTable"]],
        correlationComparisonInterpretation = function() private$.items[["correlationComparisonInterpretation"]],
        crossEntropyGuide = function() private$.items[["crossEntropyGuide"]],
        crossEntropyTable = function() private$.items[["crossEntropyTable"]],
        crossEntropyInterpretation = function() private$.items[["crossEntropyInterpretation"]],
        indirectEffectsGuide = function() private$.items[["indirectEffectsGuide"]],
        indirectEffectsTable = function() private$.items[["indirectEffectsTable"]],
        indirectEffectsInterpretation = function() private$.items[["indirectEffectsInterpretation"]],
        sampleSizeGuide = function() private$.items[["sampleSizeGuide"]],
        sampleSizeTable = function() private$.items[["sampleSizeTable"]],
        sampleSizeInterpretation = function() private$.items[["sampleSizeInterpretation"]],
        modelDiagnosticConclusionGuide = function() private$.items[["modelDiagnosticConclusionGuide"]],
        modelDiagnosticConclusionTable = function() private$.items[["modelDiagnosticConclusionTable"]],
        modelDiagnosticConclusionInterpretation = function() private$.items[["modelDiagnosticConclusionInterpretation"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Path Analysis & Structural Validation")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Path Analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelSummary",
                title="Current model",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=1,
                columns=list(
                    list(
                        `name`="nVars", 
                        `title`="Variables", 
                        `type`="integer"),
                    list(
                        `name`="nRelations", 
                        `title`="Relationships", 
                        `type`="integer"),
                    list(
                        `name`="nEndog", 
                        `title`="Endogenous variables", 
                        `type`="integer"),
                    list(
                        `name`="nExog", 
                        `title`="Exogenous variables", 
                        `type`="integer"),
                    list(
                        `name`="nCases", 
                        `title`="Complete cases", 
                        `type`="integer"),
                    list(
                        `name`="casesPerRelation", 
                        `title`="Cases per relationship", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="specifiedModel",
                title="Specified model",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                columns=list(
                    list(
                        `name`="dependent", 
                        `title`="Dependent variable", 
                        `type`="text"),
                    list(
                        `name`="predictors", 
                        `title`="Predictors", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="modelStructureGuide",
                title="Model Structure",
                visible="(showExogenous || showEndogenous)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="exogenousTable",
                title="Model Exogenous Variables",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(showExogenous)",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="outgoingPaths", 
                        `title`="Outgoing paths", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="endogenousTable",
                title="Model Endogenous Variables",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(showEndogenous)",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="incomingPaths", 
                        `title`="Direct predictors", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="validationSummary",
                title="Model Methodological Validation",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                columns=list(
                    list(
                        `name`="check", 
                        `title`="Validation", 
                        `type`="text"),
                    list(
                        `name`="status", 
                        `title`="Status", 
                        `type`="text"),
                    list(
                        `name`="details", 
                        `title`="Details", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="pathDiagram",
                title="Path Diagram (SVG)",
                width=600,
                height=400,
                renderFun=".plotPathDiagram",
                visible="(showDiagram)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="outlierGuide",
                title="Multivariate Outliers",
                visible="(isFinalized)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="outlierTable",
                title="Outlier Diagnostics",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized)",
                columns=list(
                    list(
                        `name`="case", 
                        `title`="Case", 
                        `type`="integer"),
                    list(
                        `name`="d2", 
                        `title`="Mahalanobis D\u00B2", 
                        `type`="number"),
                    list(
                        `name`="pD2", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="leverage", 
                        `title`="Leverage", 
                        `type`="number"),
                    list(
                        `name`="cooksD", 
                        `title`="Cook's distance", 
                        `type`="number"),
                    list(
                        `name`="criteria", 
                        `title`="Triggered criteria", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="equationsGuide",
                title="Model Design",
                visible="(isFinalized)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="pathCoefficients",
                title="Path Coefficients",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized && showCoeffs)",
                columns=list(
                    list(
                        `name`="dep", 
                        `title`="Endogenous Variable", 
                        `type`="text"),
                    list(
                        `name`="pred", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="est", 
                        `title`="Est.", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="beta", 
                        `title`="Beta Est.", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="coefficientsInterpretation",
                title="Applied interpretation",
                visible="(isFinalized && showCoeffs)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="rSquaredTable",
                title="Explained Variance (R\u00B2)",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized && showR2)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Endogenous Variable", 
                        `type`="text"),
                    list(
                        `name`="r2", 
                        `title`="R\u00B2", 
                        `type`="number"),
                    list(
                        `name`="adjR2", 
                        `title`="Adjusted R\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualCovarianceGuide",
                title="Residual Covariances",
                visible="(isFinalized && showCovs)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="residualCovarianceTable",
                title="Residual Covariances Among Endogenous Variables",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized && showCovs)",
                columns=list(
                    list(
                        `name`="var1", 
                        `title`="Variable 1", 
                        `type`="text"),
                    list(
                        `name`="var2", 
                        `title`="Variable 2", 
                        `type`="text"),
                    list(
                        `name`="covariance", 
                        `title`="Covariance", 
                        `type`="number"),
                    list(
                        `name`="correlation", 
                        `title`="Correlation", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualPlots",
                title="Residual Diagnostics by Equation",
                width=700,
                height=350,
                renderFun=".plotResidualHistograms",
                visible="(isFinalized && showResiduals)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="normalityGuide",
                title="Residual Normality",
                visible="(isFinalized && showResiduals)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="residualNormality",
                title="Residual Normality by Equation",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized && showResiduals)",
                columns=list(
                    list(
                        `name`="dep", 
                        `title`="Dependent Variable", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="normalityInterpretation",
                title="Applied interpretation",
                visible="(isFinalized && showResiduals)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="homoscedasticityGuide",
                title="Homoscedasticity",
                visible="(isFinalized)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="homoscedasticity",
                title="Homoscedasticity by Equation",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized)",
                columns=list(
                    list(
                        `name`="dep", 
                        `title`="Dependent Variable", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="text"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="homoscedasticityInterpretation",
                title="Applied interpretation",
                visible="(isFinalized)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="multicollinearityGuide",
                title="Multicollinearity",
                visible="(isFinalized)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="multicollinearity",
                title="Multicollinearity by Equation",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized)",
                columns=list(
                    list(
                        `name`="dep", 
                        `title`="Dependent Variable", 
                        `type`="text"),
                    list(
                        `name`="diagnostic", 
                        `title`="Diagnostic", 
                        `type`="text"),
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="multicollinearityInterpretation",
                title="Applied interpretation",
                visible="(isFinalized)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="mardiaGuide",
                title="Multivariate Normality (Mardia)",
                visible="(isFinalized)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="mardiaTable",
                title="Mardia's Multivariate Normality Test",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized)",
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Coefficient", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="text"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="mardiaInterpretation",
                title="Applied interpretation",
                visible="(isFinalized)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationMatrixGuide",
                title="Correlation Matrix",
                visible="(isFinalized && showCorrs)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="pearsonMatrixTable",
                title="Pearson Correlation Matrix (APA 7 Format)",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized && showCorrs)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dcorMatrixTable",
                title="Distance Correlation Matrix (dCor, APA 7 Format)",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized && showCorrs)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationMatrixNote",
                title=" ",
                visible="(isFinalized && showCorrs)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationComparisonGuide",
                title="Pearson / dCor / Copula Entropy Discordance Analysis",
                visible="(isFinalized && showCorrs)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="correlationComparisonTable",
                title="Pairs with a Notable Gap Between Pearson and dCor",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized && showCorrs)",
                columns=list(
                    list(
                        `name`="var1", 
                        `title`="Variable 1", 
                        `type`="text"),
                    list(
                        `name`="var2", 
                        `title`="Variable 2", 
                        `type`="text"),
                    list(
                        `name`="pearson", 
                        `title`="Pearson r", 
                        `type`="text"),
                    list(
                        `name`="dcor", 
                        `title`="dCor", 
                        `type`="text"),
                    list(
                        `name`="gap", 
                        `title`="Gap (dCor \u2212 |r|)", 
                        `type`="number"),
                    list(
                        `name`="ce", 
                        `title`="Copula Entropy", 
                        `type`="number"),
                    list(
                        `name`="ceP", 
                        `title`="p (CE)", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="ceSig", 
                        `title`="Sig. (CE)", 
                        `type`="text"),
                    list(
                        `name`="flag", 
                        `title`="Notable difference", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationComparisonInterpretation",
                title="Applied interpretation",
                visible="(isFinalized && showCorrs)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="crossEntropyGuide",
                title="Independence via Copula Entropy",
                visible="(isFinalized && showCorrs)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="crossEntropyTable",
                title="Copula Entropy Independence Test",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized && showCorrs)",
                columns=list(
                    list(
                        `name`="var1", 
                        `title`="Variable 1", 
                        `type`="text"),
                    list(
                        `name`="var2", 
                        `title`="Variable 2", 
                        `type`="text"),
                    list(
                        `name`="connected", 
                        `title`="Connected in the model", 
                        `type`="text"),
                    list(
                        `name`="ce", 
                        `title`="Copula Entropy", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="crossEntropyInterpretation",
                title="Applied interpretation",
                visible="(isFinalized && showCorrs)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="indirectEffectsGuide",
                title="Direct, Indirect, and Total Effects",
                visible="(isFinalized)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="indirectEffectsTable",
                title="Direct, Indirect, and Total Effects (Simple Mediation)",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized)",
                columns=list(
                    list(
                        `name`="x", 
                        `title`="Predictor (X)", 
                        `type`="text"),
                    list(
                        `name`="m", 
                        `title`="Mediator (M)", 
                        `type`="text"),
                    list(
                        `name`="y", 
                        `title`="Dependent Variable (Y)", 
                        `type`="text"),
                    list(
                        `name`="directBeta", 
                        `title`="Direct Effect (\u03B2)", 
                        `type`="number"),
                    list(
                        `name`="indirectBeta", 
                        `title`="Indirect Effect (\u03B2)", 
                        `type`="number"),
                    list(
                        `name`="totalBeta", 
                        `title`="Total Effect (\u03B2)", 
                        `type`="number"),
                    list(
                        `name`="sobelZ", 
                        `title`="Sobel z", 
                        `type`="number"),
                    list(
                        `name`="sobelP", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="sobelPSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="indirectEffectsInterpretation",
                title="Applied interpretation",
                visible="(isFinalized)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="sampleSizeGuide",
                title="Sample Size Adequacy",
                visible="(isFinalized)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="sampleSizeTable",
                title="Sample Size Assessment by Model Complexity",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized)",
                columns=list(
                    list(
                        `name`="criterion", 
                        `title`="Criterion (author)", 
                        `type`="text"),
                    list(
                        `name`="rule", 
                        `title`="Rule", 
                        `type`="text"),
                    list(
                        `name`="required", 
                        `title`="Required N", 
                        `type`="number"),
                    list(
                        `name`="actual", 
                        `title`="Current N", 
                        `type`="integer"),
                    list(
                        `name`="status", 
                        `title`="Status", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="sampleSizeInterpretation",
                title="Applied interpretation",
                visible="(isFinalized)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="modelDiagnosticConclusionGuide",
                title="Model Diagnostic Conclusion",
                visible="(isFinalized)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelDiagnosticConclusionTable",
                title="Model Diagnostics Summary",
                clearWith=list(
                    "vars",
                    "relations",
                    "isFinalized",
                    "permutations",
                    "permutationSeed",
                    "reportLang"),
                rows=0,
                visible="(isFinalized)",
                columns=list(
                    list(
                        `name`="area", 
                        `title`="Diagnostic Area", 
                        `type`="text"),
                    list(
                        `name`="status", 
                        `title`="Status", 
                        `type`="text"),
                    list(
                        `name`="detail", 
                        `title`="Detail", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="modelDiagnosticConclusionInterpretation",
                title="Overall Verdict",
                visible="(isFinalized)"))}))

pathCheckBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pathCheckBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "AssumptionsLab",
                name = "pathCheck",
                version = c(1,0,0),
                options = options,
                results = pathCheckResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Path Analysis & Structural Validation
#'
#' 
#' @param data .
#' @param vars Select the observed variables that will be part of the Path
#'   Analysis model.
#' @param relations Add one relationship for each path in the model. In each
#'   row, the first variable is the predictor and the second is the dependent
#'   variable (predictor → dependent). A dependent variable with several
#'   predictors is specified with several rows sharing the same second variable.
#' @param isFinalized Locks the specification and enables assumption
#'   validation and estimation. While unchecked, the model remains under
#'   construction.
#' @param showCoeffs .
#' @param showR2 .
#' @param showCorrs .
#' @param showCovs .
#' @param showResiduals .
#' @param showExogenous .
#' @param showEndogenous .
#' @param permutations Number of permutations used for the dCor and copula
#'   entropy p-value. Higher values give the p-value finer resolution (the
#'   minimum attainable is 1/(B+1)) at the cost of more computation time; 999 is
#'   reasonable for exploration, 4999 or more for final results.
#' @param permutationSeed Seed used for the permutation tests, for
#'   reproducibility.
#' @param residBinMethod .
#' @param residShowNormalCurve .
#' @param residFlagOutliers .
#' @param plotPalette .
#' @param reportLang .
#' @param showDiagram .
#' @param diagramEdgeLabel .
#' @param diagramShowErrors Shows, for each endogenous variable, a small error
#'   term (e) with an incoming arrow, along with the unexplained variance (1 -
#'   R²).
#' @param diagramOffsetLabels Offsets each path's label to one side of the
#'   arrow instead of centering it on the line.
#' @param diagramLayout .
#' @param diagramRotate Only applies to the hierarchical layout; controls
#'   which end the exogenous variables are placed at.
#' @param diagramNodeSize .
#' @param diagramShape .
#' @param diagramAbbreviate .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$specifiedModel} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modelStructureGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$exogenousTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$endogenousTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$validationSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pathDiagram} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$outlierGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$outlierTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$equationsGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pathCoefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coefficientsInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$rSquaredTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$residualCovarianceGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualCovarianceTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$residualPlots} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$normalityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualNormality} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$normalityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$homoscedasticityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$homoscedasticity} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$homoscedasticityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$multicollinearityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$multicollinearity} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$multicollinearityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$mardiaGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$mardiaTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mardiaInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationMatrixGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pearsonMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dcorMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$correlationMatrixNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationComparisonGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationComparisonTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$correlationComparisonInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$crossEntropyGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$crossEntropyTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$crossEntropyInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$indirectEffectsGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$indirectEffectsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$indirectEffectsInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$sampleSizeGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$sampleSizeTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sampleSizeInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelDiagnosticConclusionGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelDiagnosticConclusionTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modelDiagnosticConclusionInterpretation} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$modelSummary$asDF}
#'
#' \code{as.data.frame(results$modelSummary)}
#'
#' @export
pathCheck <- function(
    data,
    vars,
    relations,
    isFinalized = FALSE,
    showCoeffs = TRUE,
    showR2 = TRUE,
    showCorrs = FALSE,
    showCovs = FALSE,
    showResiduals = FALSE,
    showExogenous = TRUE,
    showEndogenous = TRUE,
    permutations = 999,
    permutationSeed = 2026,
    residBinMethod = "sturges",
    residShowNormalCurve = TRUE,
    residFlagOutliers = TRUE,
    plotPalette = "jamovi",
    reportLang = "en",
    showDiagram = TRUE,
    diagramEdgeLabel = "coef",
    diagramShowErrors = FALSE,
    diagramOffsetLabels = FALSE,
    diagramLayout = "hierarchical",
    diagramRotate = "exogLeft",
    diagramNodeSize = "medium",
    diagramShape = "ellipse",
    diagramAbbreviate = "none") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pathCheck requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- pathCheckOptions$new(
        vars = vars,
        relations = relations,
        isFinalized = isFinalized,
        showCoeffs = showCoeffs,
        showR2 = showR2,
        showCorrs = showCorrs,
        showCovs = showCovs,
        showResiduals = showResiduals,
        showExogenous = showExogenous,
        showEndogenous = showEndogenous,
        permutations = permutations,
        permutationSeed = permutationSeed,
        residBinMethod = residBinMethod,
        residShowNormalCurve = residShowNormalCurve,
        residFlagOutliers = residFlagOutliers,
        plotPalette = plotPalette,
        reportLang = reportLang,
        showDiagram = showDiagram,
        diagramEdgeLabel = diagramEdgeLabel,
        diagramShowErrors = diagramShowErrors,
        diagramOffsetLabels = diagramOffsetLabels,
        diagramLayout = diagramLayout,
        diagramRotate = diagramRotate,
        diagramNodeSize = diagramNodeSize,
        diagramShape = diagramShape,
        diagramAbbreviate = diagramAbbreviate)

    analysis <- pathCheckClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

