
# This file is automatically generated, you probably don't want to edit this

regCheckOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "regCheckOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            factors = NULL,
            reportLang = "en",
            showPlots = TRUE,
            linShowPlots = TRUE,
            linSmoother = "none",
            linShowBand = FALSE,
            linRefLine = TRUE,
            normShowPlots = TRUE,
            normQQBand = TRUE,
            normHistBins = "sturges",
            normCurveOverlay = TRUE,
            normFlagOutliers = TRUE,
            homoShowPlots = TRUE,
            homoSmoother = "none",
            homoShowBand = FALSE,
            corrShowIndividual = TRUE,
            corrShowComparative = TRUE,
            corrIndividualFit = TRUE,
            corrComparativeStyle = "dumbbell",
            corrHighlightDiscordant = TRUE,
            influenceShowPlots = TRUE,
            influenceLabelMode = "top5",
            influenceShowThreshold = TRUE,
            plotStyle = "clean",
            plotPalette = "blueOrange", ...) {

            super$initialize(
                package="AssumptionsLab",
                name="regCheck",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"),
                default="en")
            private$..showPlots <- jmvcore::OptionBool$new(
                "showPlots",
                showPlots,
                default=TRUE)
            private$..linShowPlots <- jmvcore::OptionBool$new(
                "linShowPlots",
                linShowPlots,
                default=TRUE)
            private$..linSmoother <- jmvcore::OptionList$new(
                "linSmoother",
                linSmoother,
                options=list(
                    "none",
                    "loess",
                    "linear"),
                default="none")
            private$..linShowBand <- jmvcore::OptionBool$new(
                "linShowBand",
                linShowBand,
                default=FALSE)
            private$..linRefLine <- jmvcore::OptionBool$new(
                "linRefLine",
                linRefLine,
                default=TRUE)
            private$..normShowPlots <- jmvcore::OptionBool$new(
                "normShowPlots",
                normShowPlots,
                default=TRUE)
            private$..normQQBand <- jmvcore::OptionBool$new(
                "normQQBand",
                normQQBand,
                default=TRUE)
            private$..normHistBins <- jmvcore::OptionList$new(
                "normHistBins",
                normHistBins,
                options=list(
                    "sturges",
                    "scott",
                    "fd"),
                default="sturges")
            private$..normCurveOverlay <- jmvcore::OptionBool$new(
                "normCurveOverlay",
                normCurveOverlay,
                default=TRUE)
            private$..normFlagOutliers <- jmvcore::OptionBool$new(
                "normFlagOutliers",
                normFlagOutliers,
                default=TRUE)
            private$..homoShowPlots <- jmvcore::OptionBool$new(
                "homoShowPlots",
                homoShowPlots,
                default=TRUE)
            private$..homoSmoother <- jmvcore::OptionList$new(
                "homoSmoother",
                homoSmoother,
                options=list(
                    "none",
                    "loess",
                    "linear"),
                default="none")
            private$..homoShowBand <- jmvcore::OptionBool$new(
                "homoShowBand",
                homoShowBand,
                default=FALSE)
            private$..corrShowIndividual <- jmvcore::OptionBool$new(
                "corrShowIndividual",
                corrShowIndividual,
                default=TRUE)
            private$..corrShowComparative <- jmvcore::OptionBool$new(
                "corrShowComparative",
                corrShowComparative,
                default=TRUE)
            private$..corrIndividualFit <- jmvcore::OptionBool$new(
                "corrIndividualFit",
                corrIndividualFit,
                default=TRUE)
            private$..corrComparativeStyle <- jmvcore::OptionList$new(
                "corrComparativeStyle",
                corrComparativeStyle,
                options=list(
                    "dumbbell",
                    "bar"),
                default="dumbbell")
            private$..corrHighlightDiscordant <- jmvcore::OptionBool$new(
                "corrHighlightDiscordant",
                corrHighlightDiscordant,
                default=TRUE)
            private$..influenceShowPlots <- jmvcore::OptionBool$new(
                "influenceShowPlots",
                influenceShowPlots,
                default=TRUE)
            private$..influenceLabelMode <- jmvcore::OptionList$new(
                "influenceLabelMode",
                influenceLabelMode,
                options=list(
                    "none",
                    "cooks",
                    "leverage",
                    "studres",
                    "top5"),
                default="top5")
            private$..influenceShowThreshold <- jmvcore::OptionBool$new(
                "influenceShowThreshold",
                influenceShowThreshold,
                default=TRUE)
            private$..plotStyle <- jmvcore::OptionList$new(
                "plotStyle",
                plotStyle,
                options=list(
                    "clean",
                    "bw",
                    "contrast",
                    "fullColor"),
                default="clean")
            private$..plotPalette <- jmvcore::OptionList$new(
                "plotPalette",
                plotPalette,
                options=list(
                    "blueOrange",
                    "viridis",
                    "greyscale",
                    "colorblind"),
                default="blueOrange")

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..factors)
            self$.addOption(private$..reportLang)
            self$.addOption(private$..showPlots)
            self$.addOption(private$..linShowPlots)
            self$.addOption(private$..linSmoother)
            self$.addOption(private$..linShowBand)
            self$.addOption(private$..linRefLine)
            self$.addOption(private$..normShowPlots)
            self$.addOption(private$..normQQBand)
            self$.addOption(private$..normHistBins)
            self$.addOption(private$..normCurveOverlay)
            self$.addOption(private$..normFlagOutliers)
            self$.addOption(private$..homoShowPlots)
            self$.addOption(private$..homoSmoother)
            self$.addOption(private$..homoShowBand)
            self$.addOption(private$..corrShowIndividual)
            self$.addOption(private$..corrShowComparative)
            self$.addOption(private$..corrIndividualFit)
            self$.addOption(private$..corrComparativeStyle)
            self$.addOption(private$..corrHighlightDiscordant)
            self$.addOption(private$..influenceShowPlots)
            self$.addOption(private$..influenceLabelMode)
            self$.addOption(private$..influenceShowThreshold)
            self$.addOption(private$..plotStyle)
            self$.addOption(private$..plotPalette)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        factors = function() private$..factors$value,
        reportLang = function() private$..reportLang$value,
        showPlots = function() private$..showPlots$value,
        linShowPlots = function() private$..linShowPlots$value,
        linSmoother = function() private$..linSmoother$value,
        linShowBand = function() private$..linShowBand$value,
        linRefLine = function() private$..linRefLine$value,
        normShowPlots = function() private$..normShowPlots$value,
        normQQBand = function() private$..normQQBand$value,
        normHistBins = function() private$..normHistBins$value,
        normCurveOverlay = function() private$..normCurveOverlay$value,
        normFlagOutliers = function() private$..normFlagOutliers$value,
        homoShowPlots = function() private$..homoShowPlots$value,
        homoSmoother = function() private$..homoSmoother$value,
        homoShowBand = function() private$..homoShowBand$value,
        corrShowIndividual = function() private$..corrShowIndividual$value,
        corrShowComparative = function() private$..corrShowComparative$value,
        corrIndividualFit = function() private$..corrIndividualFit$value,
        corrComparativeStyle = function() private$..corrComparativeStyle$value,
        corrHighlightDiscordant = function() private$..corrHighlightDiscordant$value,
        influenceShowPlots = function() private$..influenceShowPlots$value,
        influenceLabelMode = function() private$..influenceLabelMode$value,
        influenceShowThreshold = function() private$..influenceShowThreshold$value,
        plotStyle = function() private$..plotStyle$value,
        plotPalette = function() private$..plotPalette$value),
    private = list(
        ..dep = NA,
        ..covs = NA,
        ..factors = NA,
        ..reportLang = NA,
        ..showPlots = NA,
        ..linShowPlots = NA,
        ..linSmoother = NA,
        ..linShowBand = NA,
        ..linRefLine = NA,
        ..normShowPlots = NA,
        ..normQQBand = NA,
        ..normHistBins = NA,
        ..normCurveOverlay = NA,
        ..normFlagOutliers = NA,
        ..homoShowPlots = NA,
        ..homoSmoother = NA,
        ..homoShowBand = NA,
        ..corrShowIndividual = NA,
        ..corrShowComparative = NA,
        ..corrIndividualFit = NA,
        ..corrComparativeStyle = NA,
        ..corrHighlightDiscordant = NA,
        ..influenceShowPlots = NA,
        ..influenceLabelMode = NA,
        ..influenceShowThreshold = NA,
        ..plotStyle = NA,
        ..plotPalette = NA)
)

regCheckResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "regCheckResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        designGuide = function() private$.items[["designGuide"]],
        modelSummary = function() private$.items[["modelSummary"]],
        missingSummary = function() private$.items[["missingSummary"]],
        linearityGuide = function() private$.items[["linearityGuide"]],
        linearityPredictor = function() private$.items[["linearityPredictor"]],
        linearityModel = function() private$.items[["linearityModel"]],
        linearityInterpretation = function() private$.items[["linearityInterpretation"]],
        correlationMatrixGuide = function() private$.items[["correlationMatrixGuide"]],
        pearsonMatrixTable = function() private$.items[["pearsonMatrixTable"]],
        dcorMatrixTable = function() private$.items[["dcorMatrixTable"]],
        correlationMatrixNote = function() private$.items[["correlationMatrixNote"]],
        correlationComparisonGuide = function() private$.items[["correlationComparisonGuide"]],
        correlationComparisonTable = function() private$.items[["correlationComparisonTable"]],
        correlationComparisonInterpretation = function() private$.items[["correlationComparisonInterpretation"]],
        correlationIndividualPlot = function() private$.items[["correlationIndividualPlot"]],
        correlationIndividualGuide = function() private$.items[["correlationIndividualGuide"]],
        correlationComparativePlot = function() private$.items[["correlationComparativePlot"]],
        correlationComparativeGuide = function() private$.items[["correlationComparativeGuide"]],
        diagnosticPlotsGuide = function() private$.items[["diagnosticPlotsGuide"]],
        residualsFittedPlot = function() private$.items[["residualsFittedPlot"]],
        residualsFittedGuide = function() private$.items[["residualsFittedGuide"]],
        observedPredictedPlot = function() private$.items[["observedPredictedPlot"]],
        observedPredictedGuide = function() private$.items[["observedPredictedGuide"]],
        predictorEffectsPlot = function() private$.items[["predictorEffectsPlot"]],
        predictorEffectsGuide = function() private$.items[["predictorEffectsGuide"]],
        residualNormalityGuide = function() private$.items[["residualNormalityGuide"]],
        residualNormality = function() private$.items[["residualNormality"]],
        residualNormalityInterpretation = function() private$.items[["residualNormalityInterpretation"]],
        qqResidualsPlot = function() private$.items[["qqResidualsPlot"]],
        qqResidualsGuide = function() private$.items[["qqResidualsGuide"]],
        residualHistogramPlot = function() private$.items[["residualHistogramPlot"]],
        residualHistogramGuide = function() private$.items[["residualHistogramGuide"]],
        residualNormalCurvePlot = function() private$.items[["residualNormalCurvePlot"]],
        residualNormalCurveGuide = function() private$.items[["residualNormalCurveGuide"]],
        homoscedasticityGuide = function() private$.items[["homoscedasticityGuide"]],
        homoscedasticity = function() private$.items[["homoscedasticity"]],
        homoscedasticityInterpretation = function() private$.items[["homoscedasticityInterpretation"]],
        scaleLocationPlot = function() private$.items[["scaleLocationPlot"]],
        scaleLocationGuide = function() private$.items[["scaleLocationGuide"]],
        independenceGuide = function() private$.items[["independenceGuide"]],
        independence = function() private$.items[["independence"]],
        independenceInterpretation = function() private$.items[["independenceInterpretation"]],
        multicollinearityGuide = function() private$.items[["multicollinearityGuide"]],
        multicollinearity = function() private$.items[["multicollinearity"]],
        multicollinearityInterpretation = function() private$.items[["multicollinearityInterpretation"]],
        influenceGuide = function() private$.items[["influenceGuide"]],
        influence = function() private$.items[["influence"]],
        influenceInterpretation = function() private$.items[["influenceInterpretation"]],
        numericBoxplotsPlot = function() private$.items[["numericBoxplotsPlot"]],
        numericBoxplotsGuide = function() private$.items[["numericBoxplotsGuide"]],
        residualsLeveragePlot = function() private$.items[["residualsLeveragePlot"]],
        residualsLeverageGuide = function() private$.items[["residualsLeverageGuide"]],
        cooksDPlot = function() private$.items[["cooksDPlot"]],
        cooksDGuide = function() private$.items[["cooksDGuide"]],
        transformationsGuide = function() private$.items[["transformationsGuide"]],
        transformationNormality = function() private$.items[["transformationNormality"]],
        transformationFit = function() private$.items[["transformationFit"]],
        robustOptionsGuide = function() private$.items[["robustOptionsGuide"]],
        robustOptionsText = function() private$.items[["robustOptionsText"]],
        notes = function() private$.items[["notes"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Regresión simple y múltiple")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Regresi\u00F3n simple y m\u00FAltiple"))
            self$add(jmvcore::Html$new(
                options=options,
                name="designGuide",
                title="Modelo de regresi\u00F3n"))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelSummary",
                title="Resumen del modelo",
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Elemento", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="missingSummary",
                title="Resumen de datos faltantes",
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Elemento", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="linearityGuide",
                title="Linealidad"))
            self$add(jmvcore::Table$new(
                options=options,
                name="linearityPredictor",
                title="Linealidad por predictor num\u00E9rico",
                columns=list(
                    list(
                        `name`="predictor", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="dependent", 
                        `title`="Variable dependiente", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Prueba / criterio", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="linearityModel",
                title="Linealidad global del modelo",
                columns=list(
                    list(
                        `name`="scope", 
                        `title`="Alcance", 
                        `type`="text"),
                    list(
                        `name`="dependent", 
                        `title`="Variable dependiente", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Prueba / criterio", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="linearityInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationMatrixGuide",
                title="Matriz de correlaciones",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="pearsonMatrixTable",
                title="Matriz de correlaciones de Pearson (formato APA 7)",
                rows=0,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dcorMatrixTable",
                title="Matriz de correlaci\u00F3n de distancia (dCor, formato APA 7)",
                rows=0,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationMatrixNote",
                title=" ",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationComparisonGuide",
                title="An\u00E1lisis de discordancia Pearson / dCor / entrop\u00EDa copular",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="correlationComparisonTable",
                title="Pares con diferencia notable entre Pearson y dCor",
                rows=0,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="var1", 
                        `title`="Variable 1", 
                        `type`="text"),
                    list(
                        `name`="var2", 
                        `title`="Variable 2", 
                        `type`="text"),
                    list(
                        `name`="pearson", 
                        `title`="Pearson r", 
                        `type`="text"),
                    list(
                        `name`="dcor", 
                        `title`="dCor", 
                        `type`="text"),
                    list(
                        `name`="gap", 
                        `title`="Brecha (dCor \u2212 |r|)", 
                        `type`="number"),
                    list(
                        `name`="ce", 
                        `title`="Entrop\u00EDa copular", 
                        `type`="number"),
                    list(
                        `name`="ceP", 
                        `title`="p (CE)", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="ceSig", 
                        `title`="Sig. (CE)", 
                        `type`="text"),
                    list(
                        `name`="flag", 
                        `title`="Diferencia notable", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationComparisonInterpretation",
                title="Interpretaci\u00F3n Aplicada",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="correlationIndividualPlot",
                title="Relaci\u00F3n por par (Pearson / dCor)",
                width=620,
                height=380,
                renderFun=".plotCorrelationIndividual",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationIndividualGuide",
                title="Gu\u00EDa: Relaci\u00F3n por par (Pearson / dCor)",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="correlationComparativePlot",
                title="Comparaci\u00F3n de Pearson, dCor y entrop\u00EDa copular entre pares",
                width=620,
                height=380,
                renderFun=".plotCorrelationComparative",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationComparativeGuide",
                title="Gu\u00EDa: Comparaci\u00F3n de Pearson, dCor y entrop\u00EDa copular",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="diagnosticPlotsGuide",
                title="Gr\u00E1ficos diagn\u00F3sticos de regresi\u00F3n"))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualsFittedPlot",
                title="Residuos vs valores ajustados",
                width=560,
                height=315,
                renderFun=".plotResidualsFitted"))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualsFittedGuide",
                title="Gu\u00EDa: Residuos vs valores ajustados"))
            self$add(jmvcore::Image$new(
                options=options,
                name="observedPredictedPlot",
                title="Valores observados vs predichos",
                width=560,
                height=315,
                renderFun=".plotObservedPredicted"))
            self$add(jmvcore::Html$new(
                options=options,
                name="observedPredictedGuide",
                title="Gu\u00EDa: Valores observados vs predichos"))
            self$add(jmvcore::Image$new(
                options=options,
                name="predictorEffectsPlot",
                title="Efectos visuales de predictores num\u00E9ricos sobre la dependiente",
                width=620,
                height=350,
                renderFun=".plotPredictorEffects"))
            self$add(jmvcore::Html$new(
                options=options,
                name="predictorEffectsGuide",
                title="Gu\u00EDa: Efectos visuales de predictores num\u00E9ricos"))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualNormalityGuide",
                title="Normalidad de residuos"))
            self$add(jmvcore::Table$new(
                options=options,
                name="residualNormality",
                title="Normalidad de residuos",
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Prueba", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualNormalityInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Image$new(
                options=options,
                name="qqResidualsPlot",
                title="Q-Q plot de residuos",
                width=560,
                height=310,
                renderFun=".plotQQResiduals"))
            self$add(jmvcore::Html$new(
                options=options,
                name="qqResidualsGuide",
                title="Gu\u00EDa: Q-Q plot de residuos"))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualHistogramPlot",
                title="Histograma de residuos",
                width=560,
                height=300,
                renderFun=".plotResidualHistogram"))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualHistogramGuide",
                title="Gu\u00EDa: Histograma de residuos"))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualNormalCurvePlot",
                title="Distribuci\u00F3n observada de residuos vs curva normal te\u00F3rica",
                width=560,
                height=315,
                renderFun=".plotResidualNormalCurve"))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualNormalCurveGuide",
                title="Gu\u00EDa: Distribuci\u00F3n observada vs normal te\u00F3rica"))
            self$add(jmvcore::Html$new(
                options=options,
                name="homoscedasticityGuide",
                title="Homoscedasticidad y heterocedasticidad"))
            self$add(jmvcore::Table$new(
                options=options,
                name="homoscedasticity",
                title="Homoscedasticidad y heterocedasticidad",
                columns=list(
                    list(
                        `name`="family", 
                        `title`="Familia", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Prueba", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="homoscedasticityInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Image$new(
                options=options,
                name="scaleLocationPlot",
                title="Scale-location plot",
                width=560,
                height=315,
                renderFun=".plotScaleLocation"))
            self$add(jmvcore::Html$new(
                options=options,
                name="scaleLocationGuide",
                title="Gu\u00EDa: Scale-location plot"))
            self$add(jmvcore::Html$new(
                options=options,
                name="independenceGuide",
                title="Independencia de errores"))
            self$add(jmvcore::Table$new(
                options=options,
                name="independence",
                title="Independencia de errores",
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Prueba", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="text"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="independenceInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Html$new(
                options=options,
                name="multicollinearityGuide",
                title="Multicolinealidad",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="multicollinearity",
                title="Multicolinealidad",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="diagnostic", 
                        `title`="Diagn\u00F3stico", 
                        `type`="text"),
                    list(
                        `name`="item", 
                        `title`="Elemento", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="multicollinearityInterpretation",
                title="Interpretaci\u00F3n Aplicada",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="influenceGuide",
                title="Casos at\u00EDpicos e influyentes"))
            self$add(jmvcore::Table$new(
                options=options,
                name="influence",
                title="Casos at\u00EDpicos e influyentes",
                columns=list(
                    list(
                        `name`="case", 
                        `title`="Caso", 
                        `type`="integer"),
                    list(
                        `name`="fitted", 
                        `title`="Ajustado", 
                        `type`="number"),
                    list(
                        `name`="residual", 
                        `title`="Residuo", 
                        `type`="number"),
                    list(
                        `name`="studResidual", 
                        `title`="Residuo studentizado", 
                        `type`="number"),
                    list(
                        `name`="leverage", 
                        `title`="Leverage", 
                        `type`="number"),
                    list(
                        `name`="cooksD", 
                        `title`="Cook's D", 
                        `type`="number"),
                    list(
                        `name`="dffits", 
                        `title`="DFFITS", 
                        `type`="number"),
                    list(
                        `name`="criteria", 
                        `title`="Criterios activados", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="influenceInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Image$new(
                options=options,
                name="numericBoxplotsPlot",
                title="Boxplots de la variable dependiente y predictores num\u00E9ricos",
                width=620,
                height=360,
                renderFun=".plotNumericBoxplots"))
            self$add(jmvcore::Html$new(
                options=options,
                name="numericBoxplotsGuide",
                title="Gu\u00EDa: Boxplots de variables num\u00E9ricas"))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualsLeveragePlot",
                title="Residuos studentizados vs leverage",
                width=600,
                height=350,
                renderFun=".plotResidualsLeverage"))
            self$add(jmvcore::Html$new(
                options=options,
                name="residualsLeverageGuide",
                title="Gu\u00EDa: Residuos studentizados vs leverage"))
            self$add(jmvcore::Image$new(
                options=options,
                name="cooksDPlot",
                title="Cook's D por caso",
                width=560,
                height=300,
                renderFun=".plotCooksD"))
            self$add(jmvcore::Html$new(
                options=options,
                name="cooksDGuide",
                title="Gu\u00EDa: Cook's D por caso"))
            self$add(jmvcore::Html$new(
                options=options,
                name="transformationsGuide",
                title="Transformaciones exploratorias"))
            self$add(jmvcore::Table$new(
                options=options,
                name="transformationNormality",
                title="Normalidad de residuos por transformaci\u00F3n",
                columns=list(
                    list(
                        `name`="criterion", 
                        `title`="Criterio / prueba", 
                        `type`="text"),
                    list(
                        `name`="original", 
                        `title`="Original", 
                        `type`="text"),
                    list(
                        `name`="logTrans", 
                        `title`="log(Y)", 
                        `type`="text"),
                    list(
                        `name`="sqrtTrans", 
                        `title`="sqrt(Y)", 
                        `type`="text"),
                    list(
                        `name`="inverseTrans", 
                        `title`="1/Y", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="transformationFit",
                title="Ajuste y varianza residual por transformaci\u00F3n",
                columns=list(
                    list(
                        `name`="criterion", 
                        `title`="Criterio / prueba", 
                        `type`="text"),
                    list(
                        `name`="original", 
                        `title`="Original", 
                        `type`="text"),
                    list(
                        `name`="logTrans", 
                        `title`="log(Y)", 
                        `type`="text"),
                    list(
                        `name`="sqrtTrans", 
                        `title`="sqrt(Y)", 
                        `type`="text"),
                    list(
                        `name`="inverseTrans", 
                        `title`="1/Y", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="robustOptionsGuide",
                title="Opciones robustas y de remuestreo"))
            self$add(jmvcore::Html$new(
                options=options,
                name="robustOptionsText",
                title="Interpretaci\u00F3n metodol\u00F3gica de opciones robustas"))
            self$add(jmvcore::Html$new(
                options=options,
                name="notes",
                title="Notas y recomendaci\u00F3n"))}))

regCheckBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "regCheckBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "AssumptionsLab",
                name = "regCheck",
                version = c(1,0,0),
                options = options,
                results = regCheckResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Simple and Multiple Regression
#'
#' 
#' @param data .
#' @param dep .
#' @param covs .
#' @param factors .
#' @param reportLang .
#' @param showPlots .
#' @param linShowPlots .
#' @param linSmoother .
#' @param linShowBand .
#' @param linRefLine .
#' @param normShowPlots .
#' @param normQQBand .
#' @param normHistBins .
#' @param normCurveOverlay .
#' @param normFlagOutliers .
#' @param homoShowPlots .
#' @param homoSmoother .
#' @param homoShowBand .
#' @param corrShowIndividual .
#' @param corrShowComparative .
#' @param corrIndividualFit .
#' @param corrComparativeStyle .
#' @param corrHighlightDiscordant .
#' @param influenceShowPlots .
#' @param influenceLabelMode .
#' @param influenceShowThreshold .
#' @param plotStyle .
#' @param plotPalette .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$designGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$missingSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$linearityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$linearityPredictor} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$linearityModel} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$linearityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationMatrixGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pearsonMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dcorMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$correlationMatrixNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationComparisonGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationComparisonTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$correlationComparisonInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationIndividualPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$correlationIndividualGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationComparativePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$correlationComparativeGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$diagnosticPlotsGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualsFittedPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$residualsFittedGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$observedPredictedPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$observedPredictedGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$predictorEffectsPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$predictorEffectsGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualNormalityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualNormality} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$residualNormalityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$qqResidualsPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$qqResidualsGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualHistogramPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$residualHistogramGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualNormalCurvePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$residualNormalCurveGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$homoscedasticityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$homoscedasticity} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$homoscedasticityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$scaleLocationPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$scaleLocationGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$independenceGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$independence} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$independenceInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$multicollinearityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$multicollinearity} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$multicollinearityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$influenceGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$influence} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$influenceInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$numericBoxplotsPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$numericBoxplotsGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residualsLeveragePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$residualsLeverageGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$cooksDPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cooksDGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$transformationsGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$transformationNormality} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$transformationFit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$robustOptionsGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$robustOptionsText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$modelSummary$asDF}
#'
#' \code{as.data.frame(results$modelSummary)}
#'
#' @export
regCheck <- function(
    data,
    dep,
    covs = NULL,
    factors = NULL,
    reportLang = "en",
    showPlots = TRUE,
    linShowPlots = TRUE,
    linSmoother = "none",
    linShowBand = FALSE,
    linRefLine = TRUE,
    normShowPlots = TRUE,
    normQQBand = TRUE,
    normHistBins = "sturges",
    normCurveOverlay = TRUE,
    normFlagOutliers = TRUE,
    homoShowPlots = TRUE,
    homoSmoother = "none",
    homoShowBand = FALSE,
    corrShowIndividual = TRUE,
    corrShowComparative = TRUE,
    corrIndividualFit = TRUE,
    corrComparativeStyle = "dumbbell",
    corrHighlightDiscordant = TRUE,
    influenceShowPlots = TRUE,
    influenceLabelMode = "top5",
    influenceShowThreshold = TRUE,
    plotStyle = "clean",
    plotPalette = "blueOrange") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("regCheck requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(factors), factors, NULL))

    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- regCheckOptions$new(
        dep = dep,
        covs = covs,
        factors = factors,
        reportLang = reportLang,
        showPlots = showPlots,
        linShowPlots = linShowPlots,
        linSmoother = linSmoother,
        linShowBand = linShowBand,
        linRefLine = linRefLine,
        normShowPlots = normShowPlots,
        normQQBand = normQQBand,
        normHistBins = normHistBins,
        normCurveOverlay = normCurveOverlay,
        normFlagOutliers = normFlagOutliers,
        homoShowPlots = homoShowPlots,
        homoSmoother = homoSmoother,
        homoShowBand = homoShowBand,
        corrShowIndividual = corrShowIndividual,
        corrShowComparative = corrShowComparative,
        corrIndividualFit = corrIndividualFit,
        corrComparativeStyle = corrComparativeStyle,
        corrHighlightDiscordant = corrHighlightDiscordant,
        influenceShowPlots = influenceShowPlots,
        influenceLabelMode = influenceLabelMode,
        influenceShowThreshold = influenceShowThreshold,
        plotStyle = plotStyle,
        plotPalette = plotPalette)

    analysis <- regCheckClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

