
# This file is automatically generated, you probably don't want to edit this

relatedCheckOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "relatedCheckOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            measures = NULL,
            reportLang = "en",
            showProfilePlot = FALSE,
            showDifferencePlots = FALSE,
            showNormalityPlots = FALSE,
            plotPalette = "jamovi", ...) {

            super$initialize(
                package="AssumptionsLab",
                name="relatedCheck",
                requiresData=TRUE,
                ...)

            private$..measures <- jmvcore::OptionVariables$new(
                "measures",
                measures,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"),
                default="en")
            private$..showProfilePlot <- jmvcore::OptionBool$new(
                "showProfilePlot",
                showProfilePlot,
                default=FALSE)
            private$..showDifferencePlots <- jmvcore::OptionBool$new(
                "showDifferencePlots",
                showDifferencePlots,
                default=FALSE)
            private$..showNormalityPlots <- jmvcore::OptionBool$new(
                "showNormalityPlots",
                showNormalityPlots,
                default=FALSE)
            private$..plotPalette <- jmvcore::OptionList$new(
                "plotPalette",
                plotPalette,
                options=list(
                    "jamovi",
                    "colorblind",
                    "viridis"),
                default="jamovi")

            self$.addOption(private$..measures)
            self$.addOption(private$..reportLang)
            self$.addOption(private$..showProfilePlot)
            self$.addOption(private$..showDifferencePlots)
            self$.addOption(private$..showNormalityPlots)
            self$.addOption(private$..plotPalette)
        }),
    active = list(
        measures = function() private$..measures$value,
        reportLang = function() private$..reportLang$value,
        showProfilePlot = function() private$..showProfilePlot$value,
        showDifferencePlots = function() private$..showDifferencePlots$value,
        showNormalityPlots = function() private$..showNormalityPlots$value,
        plotPalette = function() private$..plotPalette$value),
    private = list(
        ..measures = NA,
        ..reportLang = NA,
        ..showProfilePlot = NA,
        ..showDifferencePlots = NA,
        ..showNormalityPlots = NA,
        ..plotPalette = NA)
)

relatedCheckResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "relatedCheckResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        designGuide = function() private$.items[["designGuide"]],
        designSummary = function() private$.items[["designSummary"]],
        descriptiveSummary = function() private$.items[["descriptiveSummary"]],
        profilePlot = function() private$.items[["profilePlot"]],
        differencePlot = function() private$.items[["differencePlot"]],
        normalityPlot = function() private$.items[["normalityPlot"]],
        normalCurvePlot = function() private$.items[["normalCurvePlot"]],
        differenceGuide = function() private$.items[["differenceGuide"]],
        differenceSummary = function() private$.items[["differenceSummary"]],
        normalityGuide = function() private$.items[["normalityGuide"]],
        normality = function() private$.items[["normality"]],
        normalitySummary = function() private$.items[["normalitySummary"]],
        normalityRecommendation = function() private$.items[["normalityRecommendation"]],
        normalityInterpretation = function() private$.items[["normalityInterpretation"]],
        symmetryGuide = function() private$.items[["symmetryGuide"]],
        symmetry = function() private$.items[["symmetry"]],
        symmetryInterpretation = function() private$.items[["symmetryInterpretation"]],
        sphericityGuide = function() private$.items[["sphericityGuide"]],
        sphericity = function() private$.items[["sphericity"]],
        sphericityInterpretation = function() private$.items[["sphericityInterpretation"]],
        correlationMatrixGuide = function() private$.items[["correlationMatrixGuide"]],
        pearsonMatrixTable = function() private$.items[["pearsonMatrixTable"]],
        dcorMatrixTable = function() private$.items[["dcorMatrixTable"]],
        correlationMatrixNote = function() private$.items[["correlationMatrixNote"]],
        correlationComparisonGuide = function() private$.items[["correlationComparisonGuide"]],
        correlationComparisonTable = function() private$.items[["correlationComparisonTable"]],
        correlationComparisonInterpretation = function() private$.items[["correlationComparisonInterpretation"]],
        outliersGuide = function() private$.items[["outliersGuide"]],
        outliers = function() private$.items[["outliers"]],
        outliersInterpretation = function() private$.items[["outliersInterpretation"]],
        methodGuide = function() private$.items[["methodGuide"]],
        methodOptions = function() private$.items[["methodOptions"]],
        methodWhen = function() private$.items[["methodWhen"]],
        notes = function() private$.items[["notes"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Related groups")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Related groups"))
            self$add(jmvcore::Html$new(
                options=options,
                name="designGuide",
                title="Related-groups design"))
            self$add(jmvcore::Table$new(
                options=options,
                name="designSummary",
                title="Design summary",
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="descriptiveSummary",
                title="Descriptives by measurement",
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measurement", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="n", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="M", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="median", 
                        `title`="Mdn", 
                        `type`="number"),
                    list(
                        `name`="min", 
                        `title`="Min", 
                        `type`="number"),
                    list(
                        `name`="max", 
                        `title`="Max", 
                        `type`="number"),
                    list(
                        `name`="missing", 
                        `title`="Missing", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="profilePlot",
                title="Profile of related measurements",
                width=560,
                height=315,
                renderFun=".plotProfile",
                visible="(showProfilePlot)",
                clearWith=list(
                    "measures",
                    "showProfilePlot",
                    "plotStyle",
                    "plotPalette",
                    "reportLang")))
            self$add(jmvcore::Image$new(
                options=options,
                name="differencePlot",
                title="Distribution of paired differences",
                width=560,
                height=315,
                renderFun=".plotDifferences",
                visible="(showDifferencePlots)",
                clearWith=list(
                    "measures",
                    "showDifferencePlots",
                    "plotStyle",
                    "plotPalette",
                    "reportLang")))
            self$add(jmvcore::Image$new(
                options=options,
                name="normalityPlot",
                title="Q-Q plots of paired differences",
                width=620,
                height=360,
                renderFun=".plotNormality",
                visible="(showNormalityPlots)",
                clearWith=list(
                    "measures",
                    "showNormalityPlots",
                    "plotStyle",
                    "reportLang")))
            self$add(jmvcore::Image$new(
                options=options,
                name="normalCurvePlot",
                title="Observed distribution vs theoretical normal",
                width=620,
                height=360,
                renderFun=".plotNormalCurve",
                visible="(showNormalityPlots)",
                clearWith=list(
                    "measures",
                    "showNormalityPlots",
                    "plotStyle",
                    "reportLang")))
            self$add(jmvcore::Html$new(
                options=options,
                name="differenceGuide",
                title="Paired differences"))
            self$add(jmvcore::Table$new(
                options=options,
                name="differenceSummary",
                title="Summary of paired differences",
                columns=list(
                    list(
                        `name`="comparison", 
                        `title`="Comparison", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="n", 
                        `type`="integer"),
                    list(
                        `name`="meanDiff", 
                        `title`="M difference", 
                        `type`="number"),
                    list(
                        `name`="sdDiff", 
                        `title`="SD difference", 
                        `type`="number"),
                    list(
                        `name`="medianDiff", 
                        `title`="Mdn difference", 
                        `type`="number"),
                    list(
                        `name`="minDiff", 
                        `title`="Min", 
                        `type`="number"),
                    list(
                        `name`="maxDiff", 
                        `title`="Max", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="normalityGuide",
                title="Normality of differences/residuals"))
            self$add(jmvcore::Table$new(
                options=options,
                name="normality",
                title="Normality of differences/residuals",
                columns=list(
                    list(
                        `name`="scope", 
                        `title`="Scope", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="normalitySummary",
                title="Normality summary by comparison",
                columns=list(
                    list(
                        `name`="comparison", 
                        `title`="Comparison", 
                        `type`="text"),
                    list(
                        `name`="tests", 
                        `title`="Valid tests", 
                        `type`="integer"),
                    list(
                        `name`="significant", 
                        `title`="Significant tests", 
                        `type`="integer"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="normalityRecommendation",
                title="Recommendation"))
            self$add(jmvcore::Html$new(
                options=options,
                name="normalityInterpretation",
                title="Applied interpretation"))
            self$add(jmvcore::Html$new(
                options=options,
                name="symmetryGuide",
                title="Symmetry of differences"))
            self$add(jmvcore::Table$new(
                options=options,
                name="symmetry",
                title="Symmetry of differences",
                columns=list(
                    list(
                        `name`="comparison", 
                        `title`="Comparison", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="symmetryInterpretation",
                title="Applied interpretation"))
            self$add(jmvcore::Html$new(
                options=options,
                name="sphericityGuide",
                title="Sphericity",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="sphericity",
                title="Sphericity and corrections",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="diagnostic", 
                        `title`="Diagnostic", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="text"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="sphericityInterpretation",
                title="Applied interpretation",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationMatrixGuide",
                title="Correlation matrix",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="pearsonMatrixTable",
                title="Pearson correlation matrix (APA 7 format)",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dcorMatrixTable",
                title="Distance correlation matrix (dCor, APA 7 format)",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationMatrixNote",
                title=" ",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationComparisonGuide",
                title="Pearson / dCor / copula entropy discordance analysis",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="correlationComparisonTable",
                title="Pairs with a notable gap between Pearson and dCor",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="var1", 
                        `title`="Variable 1", 
                        `type`="text"),
                    list(
                        `name`="var2", 
                        `title`="Variable 2", 
                        `type`="text"),
                    list(
                        `name`="pearson", 
                        `title`="Pearson r", 
                        `type`="text"),
                    list(
                        `name`="dcor", 
                        `title`="dCor", 
                        `type`="text"),
                    list(
                        `name`="gap", 
                        `title`="Gap (dCor \u2212 |r|)", 
                        `type`="number"),
                    list(
                        `name`="ce", 
                        `title`="Copula entropy", 
                        `type`="number"),
                    list(
                        `name`="ceP", 
                        `title`="p (CE)", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="ceSig", 
                        `title`="Sig. (CE)", 
                        `type`="text"),
                    list(
                        `name`="flag", 
                        `title`="Notable difference", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationComparisonInterpretation",
                title="Applied interpretation",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="outliersGuide",
                title="Outliers in differences"))
            self$add(jmvcore::Table$new(
                options=options,
                name="outliers",
                title="Outliers in differences",
                columns=list(
                    list(
                        `name`="case", 
                        `title`="Case", 
                        `type`="integer"),
                    list(
                        `name`="comparison", 
                        `title`="Comparison", 
                        `type`="text"),
                    list(
                        `name`="difference", 
                        `title`="Difference", 
                        `type`="number"),
                    list(
                        `name`="criterion", 
                        `title`="Triggered criterion", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="outliersInterpretation",
                title="Applied interpretation"))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodGuide",
                title="Test selection"))
            self$add(jmvcore::Table$new(
                options=options,
                name="methodOptions",
                title="Methodological options",
                columns=list(
                    list(
                        `name`="design", 
                        `title`="Design", 
                        `type`="text"),
                    list(
                        `name`="evidence", 
                        `title`="Evidence", 
                        `type`="text"),
                    list(
                        `name`="suggestion", 
                        `title`="Suggested test", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodWhen",
                title=""))
            self$add(jmvcore::Html$new(
                options=options,
                name="notes",
                title="Notes and recommendation"))}))

relatedCheckBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "relatedCheckBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "AssumptionsLab",
                name = "relatedCheck",
                version = c(1,0,0),
                options = options,
                results = relatedCheckResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Related Groups
#'
#' 
#' @param data .
#' @param measures .
#' @param reportLang .
#' @param showProfilePlot .
#' @param showDifferencePlots .
#' @param showNormalityPlots .
#' @param plotPalette .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$designGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$designSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$descriptiveSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$profilePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$differencePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$normalityPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$normalCurvePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$differenceGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$differenceSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$normalityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$normality} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$normalitySummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$normalityRecommendation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$normalityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$symmetryGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$symmetry} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$symmetryInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$sphericityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$sphericity} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sphericityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationMatrixGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pearsonMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dcorMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$correlationMatrixNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationComparisonGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationComparisonTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$correlationComparisonInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$outliersGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$outliers} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$outliersInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$methodGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$methodOptions} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$methodWhen} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$designSummary$asDF}
#'
#' \code{as.data.frame(results$designSummary)}
#'
#' @export
relatedCheck <- function(
    data,
    measures = NULL,
    reportLang = "en",
    showProfilePlot = FALSE,
    showDifferencePlots = FALSE,
    showNormalityPlots = FALSE,
    plotPalette = "jamovi") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("relatedCheck requires jmvcore to be installed (restart may be required)")

    if ( ! missing(measures)) measures <- jmvcore::resolveQuo(jmvcore::enquo(measures))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(measures), measures, NULL))


    options <- relatedCheckOptions$new(
        measures = measures,
        reportLang = reportLang,
        showProfilePlot = showProfilePlot,
        showDifferencePlots = showDifferencePlots,
        showNormalityPlots = showNormalityPlots,
        plotPalette = plotPalette)

    analysis <- relatedCheckClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

