
# This file is automatically generated, you probably don't want to edit this

relatedCheckOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "relatedCheckOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            measures = NULL,
            reportLang = "en",
            showProfilePlot = FALSE,
            showDifferencePlots = FALSE,
            showNormalityPlots = FALSE,
            plotStyle = "clean",
            plotPalette = "blueOrange", ...) {

            super$initialize(
                package="AssumptionsLab",
                name="relatedCheck",
                requiresData=TRUE,
                ...)

            private$..measures <- jmvcore::OptionVariables$new(
                "measures",
                measures,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"),
                default="en")
            private$..showProfilePlot <- jmvcore::OptionBool$new(
                "showProfilePlot",
                showProfilePlot,
                default=FALSE)
            private$..showDifferencePlots <- jmvcore::OptionBool$new(
                "showDifferencePlots",
                showDifferencePlots,
                default=FALSE)
            private$..showNormalityPlots <- jmvcore::OptionBool$new(
                "showNormalityPlots",
                showNormalityPlots,
                default=FALSE)
            private$..plotStyle <- jmvcore::OptionList$new(
                "plotStyle",
                plotStyle,
                options=list(
                    "clean",
                    "bw",
                    "contrast",
                    "fullColor"),
                default="clean")
            private$..plotPalette <- jmvcore::OptionList$new(
                "plotPalette",
                plotPalette,
                options=list(
                    "blueOrange",
                    "viridis",
                    "greyscale",
                    "colorblind"),
                default="blueOrange")

            self$.addOption(private$..measures)
            self$.addOption(private$..reportLang)
            self$.addOption(private$..showProfilePlot)
            self$.addOption(private$..showDifferencePlots)
            self$.addOption(private$..showNormalityPlots)
            self$.addOption(private$..plotStyle)
            self$.addOption(private$..plotPalette)
        }),
    active = list(
        measures = function() private$..measures$value,
        reportLang = function() private$..reportLang$value,
        showProfilePlot = function() private$..showProfilePlot$value,
        showDifferencePlots = function() private$..showDifferencePlots$value,
        showNormalityPlots = function() private$..showNormalityPlots$value,
        plotStyle = function() private$..plotStyle$value,
        plotPalette = function() private$..plotPalette$value),
    private = list(
        ..measures = NA,
        ..reportLang = NA,
        ..showProfilePlot = NA,
        ..showDifferencePlots = NA,
        ..showNormalityPlots = NA,
        ..plotStyle = NA,
        ..plotPalette = NA)
)

relatedCheckResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "relatedCheckResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        designGuide = function() private$.items[["designGuide"]],
        designSummary = function() private$.items[["designSummary"]],
        descriptiveSummary = function() private$.items[["descriptiveSummary"]],
        profilePlot = function() private$.items[["profilePlot"]],
        differencePlot = function() private$.items[["differencePlot"]],
        normalityPlot = function() private$.items[["normalityPlot"]],
        normalCurvePlot = function() private$.items[["normalCurvePlot"]],
        differenceGuide = function() private$.items[["differenceGuide"]],
        differenceSummary = function() private$.items[["differenceSummary"]],
        normalityGuide = function() private$.items[["normalityGuide"]],
        normality = function() private$.items[["normality"]],
        normalitySummary = function() private$.items[["normalitySummary"]],
        normalityRecommendation = function() private$.items[["normalityRecommendation"]],
        normalityInterpretation = function() private$.items[["normalityInterpretation"]],
        symmetryGuide = function() private$.items[["symmetryGuide"]],
        symmetry = function() private$.items[["symmetry"]],
        symmetryInterpretation = function() private$.items[["symmetryInterpretation"]],
        sphericityGuide = function() private$.items[["sphericityGuide"]],
        sphericity = function() private$.items[["sphericity"]],
        sphericityInterpretation = function() private$.items[["sphericityInterpretation"]],
        correlationMatrixGuide = function() private$.items[["correlationMatrixGuide"]],
        pearsonMatrixTable = function() private$.items[["pearsonMatrixTable"]],
        dcorMatrixTable = function() private$.items[["dcorMatrixTable"]],
        correlationMatrixNote = function() private$.items[["correlationMatrixNote"]],
        correlationComparisonGuide = function() private$.items[["correlationComparisonGuide"]],
        correlationComparisonTable = function() private$.items[["correlationComparisonTable"]],
        correlationComparisonInterpretation = function() private$.items[["correlationComparisonInterpretation"]],
        outliersGuide = function() private$.items[["outliersGuide"]],
        outliers = function() private$.items[["outliers"]],
        outliersInterpretation = function() private$.items[["outliersInterpretation"]],
        methodGuide = function() private$.items[["methodGuide"]],
        methodOptions = function() private$.items[["methodOptions"]],
        methodWhen = function() private$.items[["methodWhen"]],
        notes = function() private$.items[["notes"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Grupos relacionados")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Grupos relacionados"))
            self$add(jmvcore::Html$new(
                options=options,
                name="designGuide",
                title="Dise\u00F1o de grupos relacionados"))
            self$add(jmvcore::Table$new(
                options=options,
                name="designSummary",
                title="Resumen del dise\u00F1o",
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Elemento", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="descriptiveSummary",
                title="Descriptivos por medici\u00F3n",
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Medici\u00F3n", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="n", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="M", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="median", 
                        `title`="Mdn", 
                        `type`="number"),
                    list(
                        `name`="min", 
                        `title`="Min", 
                        `type`="number"),
                    list(
                        `name`="max", 
                        `title`="Max", 
                        `type`="number"),
                    list(
                        `name`="missing", 
                        `title`="Faltantes", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="profilePlot",
                title="Perfil de mediciones relacionadas",
                requiresData=TRUE,
                width=560,
                height=315,
                renderFun=".plotProfile",
                visible="(showProfilePlot)",
                clearWith=list(
                    "measures",
                    "showProfilePlot",
                    "plotStyle",
                    "plotPalette",
                    "reportLang")))
            self$add(jmvcore::Image$new(
                options=options,
                name="differencePlot",
                title="Distribuci\u00F3n de diferencias pareadas",
                requiresData=TRUE,
                width=560,
                height=315,
                renderFun=".plotDifferences",
                visible="(showDifferencePlots)",
                clearWith=list(
                    "measures",
                    "showDifferencePlots",
                    "plotStyle",
                    "plotPalette",
                    "reportLang")))
            self$add(jmvcore::Image$new(
                options=options,
                name="normalityPlot",
                title="Q-Q plots de diferencias pareadas",
                requiresData=TRUE,
                width=620,
                height=360,
                renderFun=".plotNormality",
                visible="(showNormalityPlots)",
                clearWith=list(
                    "measures",
                    "showNormalityPlots",
                    "plotStyle",
                    "reportLang")))
            self$add(jmvcore::Image$new(
                options=options,
                name="normalCurvePlot",
                title="Distribuci\u00F3n observada vs normal te\u00F3rica",
                requiresData=TRUE,
                width=620,
                height=360,
                renderFun=".plotNormalCurve",
                visible="(showNormalityPlots)",
                clearWith=list(
                    "measures",
                    "showNormalityPlots",
                    "plotStyle",
                    "reportLang")))
            self$add(jmvcore::Html$new(
                options=options,
                name="differenceGuide",
                title="Diferencias pareadas"))
            self$add(jmvcore::Table$new(
                options=options,
                name="differenceSummary",
                title="Resumen de diferencias pareadas",
                columns=list(
                    list(
                        `name`="comparison", 
                        `title`="Comparaci\u00F3n", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="n", 
                        `type`="integer"),
                    list(
                        `name`="meanDiff", 
                        `title`="M diferencia", 
                        `type`="number"),
                    list(
                        `name`="sdDiff", 
                        `title`="SD diferencia", 
                        `type`="number"),
                    list(
                        `name`="medianDiff", 
                        `title`="Mdn diferencia", 
                        `type`="number"),
                    list(
                        `name`="minDiff", 
                        `title`="Min", 
                        `type`="number"),
                    list(
                        `name`="maxDiff", 
                        `title`="Max", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="normalityGuide",
                title="Normalidad de diferencias/residuos"))
            self$add(jmvcore::Table$new(
                options=options,
                name="normality",
                title="Normalidad de diferencias/residuos",
                columns=list(
                    list(
                        `name`="scope", 
                        `title`="Alcance", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Prueba", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="normalitySummary",
                title="Resumen de normalidad por comparaci\u00F3n",
                columns=list(
                    list(
                        `name`="comparison", 
                        `title`="Comparaci\u00F3n", 
                        `type`="text"),
                    list(
                        `name`="tests", 
                        `title`="Pruebas v\u00E1lidas", 
                        `type`="integer"),
                    list(
                        `name`="significant", 
                        `title`="Pruebas significativas", 
                        `type`="integer"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretaci\u00F3n", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="normalityRecommendation",
                title="Recomendaci\u00F3n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="normalityInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Html$new(
                options=options,
                name="symmetryGuide",
                title="Simetr\u00EDa de diferencias"))
            self$add(jmvcore::Table$new(
                options=options,
                name="symmetry",
                title="Simetr\u00EDa de diferencias",
                columns=list(
                    list(
                        `name`="comparison", 
                        `title`="Comparaci\u00F3n", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="symmetryInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Html$new(
                options=options,
                name="sphericityGuide",
                title="Esfericidad",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="sphericity",
                title="Esfericidad y correcciones",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="diagnostic", 
                        `title`="Diagn\u00F3stico", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Estad\u00EDstico", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Valor", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="text"),
                    list(
                        `name`="pSig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="sphericityInterpretation",
                title="Interpretaci\u00F3n Aplicada",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationMatrixGuide",
                title="Matriz de correlaciones",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="pearsonMatrixTable",
                title="Matriz de correlaciones de Pearson (formato APA 7)",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dcorMatrixTable",
                title="Matriz de correlaci\u00F3n de distancia (dCor, formato APA 7)",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationMatrixNote",
                title=" ",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationComparisonGuide",
                title="An\u00E1lisis de discordancia Pearson / dCor / entrop\u00EDa copular",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="correlationComparisonTable",
                title="Pares con diferencia notable entre Pearson y dCor",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="var1", 
                        `title`="Variable 1", 
                        `type`="text"),
                    list(
                        `name`="var2", 
                        `title`="Variable 2", 
                        `type`="text"),
                    list(
                        `name`="pearson", 
                        `title`="Pearson r", 
                        `type`="text"),
                    list(
                        `name`="dcor", 
                        `title`="dCor", 
                        `type`="text"),
                    list(
                        `name`="gap", 
                        `title`="Brecha (dCor \u2212 |r|)", 
                        `type`="number"),
                    list(
                        `name`="ce", 
                        `title`="Entrop\u00EDa copular", 
                        `type`="number"),
                    list(
                        `name`="ceP", 
                        `title`="p (CE)", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="ceSig", 
                        `title`="Sig. (CE)", 
                        `type`="text"),
                    list(
                        `name`="flag", 
                        `title`="Diferencia notable", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="correlationComparisonInterpretation",
                title="Interpretaci\u00F3n Aplicada",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="outliersGuide",
                title="Casos at\u00EDpicos en diferencias"))
            self$add(jmvcore::Table$new(
                options=options,
                name="outliers",
                title="Casos at\u00EDpicos en diferencias",
                columns=list(
                    list(
                        `name`="case", 
                        `title`="Caso", 
                        `type`="integer"),
                    list(
                        `name`="comparison", 
                        `title`="Comparaci\u00F3n", 
                        `type`="text"),
                    list(
                        `name`="difference", 
                        `title`="Diferencia", 
                        `type`="number"),
                    list(
                        `name`="criterion", 
                        `title`="Criterio activado", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="outliersInterpretation",
                title="Interpretaci\u00F3n Aplicada"))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodGuide",
                title="Selecci\u00F3n de prueba"))
            self$add(jmvcore::Table$new(
                options=options,
                name="methodOptions",
                title="Opciones metodol\u00F3gicas",
                columns=list(
                    list(
                        `name`="design", 
                        `title`="Dise\u00F1o", 
                        `type`="text"),
                    list(
                        `name`="evidence", 
                        `title`="Evidencia", 
                        `type`="text"),
                    list(
                        `name`="suggestion", 
                        `title`="Prueba sugerida", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodWhen",
                title=""))
            self$add(jmvcore::Html$new(
                options=options,
                name="notes",
                title="Notas y recomendaci\u00F3n"))}))

relatedCheckBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "relatedCheckBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "AssumptionsLab",
                name = "relatedCheck",
                version = c(1,0,0),
                options = options,
                results = relatedCheckResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Related Groups
#'
#' 
#' @param data .
#' @param measures .
#' @param reportLang .
#' @param showProfilePlot .
#' @param showDifferencePlots .
#' @param showNormalityPlots .
#' @param plotStyle .
#' @param plotPalette .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$designGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$designSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$descriptiveSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$profilePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$differencePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$normalityPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$normalCurvePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$differenceGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$differenceSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$normalityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$normality} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$normalitySummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$normalityRecommendation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$normalityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$symmetryGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$symmetry} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$symmetryInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$sphericityGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$sphericity} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sphericityInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationMatrixGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pearsonMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dcorMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$correlationMatrixNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationComparisonGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$correlationComparisonTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$correlationComparisonInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$outliersGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$outliers} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$outliersInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$methodGuide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$methodOptions} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$methodWhen} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$designSummary$asDF}
#'
#' \code{as.data.frame(results$designSummary)}
#'
#' @export
relatedCheck <- function(
    data,
    measures = NULL,
    reportLang = "en",
    showProfilePlot = FALSE,
    showDifferencePlots = FALSE,
    showNormalityPlots = FALSE,
    plotStyle = "clean",
    plotPalette = "blueOrange") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("relatedCheck requires jmvcore to be installed (restart may be required)")

    if ( ! missing(measures)) measures <- jmvcore::resolveQuo(jmvcore::enquo(measures))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(measures), measures, NULL))


    options <- relatedCheckOptions$new(
        measures = measures,
        reportLang = reportLang,
        showProfilePlot = showProfilePlot,
        showDifferencePlots = showDifferencePlots,
        showNormalityPlots = showNormalityPlots,
        plotStyle = plotStyle,
        plotPalette = plotPalette)

    analysis <- relatedCheckClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

